### ISSUE TITLE
[Bugfix 2.0.x] Cannot use EEPROM Saving or Loading with Re-arm+Ramps1.4

### ISSUE THREAD

**Issue by chrisjenda** [MarlinFirmware/Marlin#10048]
### Description

Cannot use EEPROM on Re-Arm+Ramps 1.4 with Commit/Pull: 82a02a3/10044

### Steps to Reproduce

1. [First Step]
Setup Marlin Config as Follows:
//  Set Baud Rate to 230400
//  Set MB to Re-Arm + Ramps EFB
//  Set Filiment Diameter to 1.75
//  Enable ATX Power Supply Control
//  Enable EEPROM
//  Enable REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER
//  Enable Dual Z Stepper drivers (Advanced Config)
2. [Second Step]
Compile Marlin and Upload to Re-Arm
3. [Third Step]
Issue an M502 to reset to hardcoded and then run an M500 to get the error.

**Expected behavior:**
M500 Saves EEPROM Settings and allows an M503 to Load them.

**Actual behavior:**
When sending an M502+M500 Gcode Command with "DEBUG_EEPROM_READWRITE" Enabled the following is returned:

19:11:50.293 : M502
19:11:51.125 : echo:Hardcoded Default Settings Loaded
19:11:54.401 : M500
19:11:54.958 : write_data(100,268468032,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : Error:Field esteppers mismatch.
19:11:54.958 : write_data(102,268468014,1...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268444280,16...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268444300,16...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268444352,16...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268442908,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268444328,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268444324,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268444316,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268444348,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268444320,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268444384,16...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268442836,12...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268468040,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268468028,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268468015,1...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268468016,1...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268468028,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268468028,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268468028,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268468028,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268468028,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268468028,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268468028,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268468028,4...)
19:11:54.958 : f_lseek()=9
19:11:54.958 : write_data(102,268468028,4...)
19:11:54.958 : f_lseek()=9
19:11:54.959 : write_data(102,268468044,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468017,1...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468018,1...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468068,8...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468060,8...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468019,1...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468020,1...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268442512,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268442504,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268442508,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268444588,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268444584,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268444580,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.959 : f_lseek()=9
19:11:54.959 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468048,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468024,2...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468021,1...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468112,32...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268441257,1...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468088,22...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468052,6...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468076,12...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.960 : f_lseek()=9
19:11:54.960 : write_data(102,268468028,4...)
19:11:54.961 : f_lseek()=9
19:11:54.961 : write_data(102,268468028,4...)
19:11:54.961 : f_lseek()=9
19:11:54.961 : write_data(102,268468028,4...)
19:11:54.961 : f_lseek()=9
19:11:54.961 : write_data(102,268468028,4...)
19:11:54.961 : f_lseek()=9
19:11:54.961 : write_data(102,268468028,4...)
19:11:54.961 : f_lseek()=9
19:11:54.961 : write_data(102,268468028,4...)
19:11:54.961 : f_lseek()=9
19:11:54.961 : write_data(102,268468028,4...)
19:11:54.961 : f_lseek()=9
19:11:54.961 : write_data(102,268468028,4...)
19:11:54.961 : f_lseek()=9
19:11:54.961 : write_data(102,268468028,4...)
19:11:54.961 : f_lseek()=9
19:11:54.961 : write_data(102,268468028,4...)
19:11:54.961 : f_lseek()=9
19:11:54.961 : write_data(102,268468028,4...)
19:11:54.961 : f_lseek()=9
19:11:54.961 : write_data(102,268468028,4...)
19:11:54.961 : f_lseek()=9
19:11:54.961 : write_data(102,268468028,4...)
19:11:54.961 : f_lseek()=9
19:11:54.961 : write_data(102,268468028,4...)
19:11:54.961 : f_lseek()=9

**Comment by As3uS** [comment]
Hi there,
Excactly the same problem here with MKS Sbase + Reprap discount FullGraphic. 
Send M500 with ponterface cause same listing error f_lseek()=9 / write_data(102,268468028,4...)
and Mks Reboot few second after.

I use the last Bugfix 2.0

**Comment by Roxy-3D** [comment]
Do you have an SD Memory card plugged into the Re-ARM board?   That is where the EEPROM data is stored.

**Comment by apballard** [comment]
Hi all, I’m having issues myself, but not sure if it’s the same problem.

I can save my settings to sd card, I can initialize it, but in restart my printer will not boot up.  It just sits with blank screen. If I remove SD card or delete eeprom file it works. Not sure if related.

**Comment by chrisjenda** [comment]
@Roxy-3D Yes, I have an SD card inserted as that is what I used to flash the marlin bin file.

**Comment by p3p** [comment]
@apballard if you have UBL enabled can you try the current bugfix-2.0.x, there was an issue with the watchdog resetting while outputting the current UBL mesh over serial during boot, (there has to be a long delay per output line for some reason). 

@chrisjenda I'm not sure whats going on here, well I know it's not managing to open the eeprom.dat file for writing, it stands to reason if the bootloader can flash from the sdcard Marlin should be able to read/write it, but to grasp at straws do you have any other sd cards to test with?

**Comment by apballard** [comment]
@p3p I think that might be it, let me try.

**Comment by chrisjenda** [comment]
I think it has something to do with an update as I belive pull 8917 works fine, but that is pretty far back.  If I run the Command with debugging enabled it gives "19:11:54.958 : Error:Field esteppers mismatch."  So must be a problem with the esteppers field, whatever that means.

**Comment by As3uS** [comment]
If it's a Read/Write error can i try catch error on file persistent_store_impl.ccp 
with the infos in comment ?

 if(res == FR_DISK_ERR){ SERIAL_PROTOCOL("A hard error occurred in the low level disk I/O layer\n\n");}
 if(res == FR_INT_ERR){ SERIAL_PROTOCOL("Assertion failed\n");}
 if(res == FR_NOT_READY){ SERIAL_PROTOCOL("The physical drive cannot work\n");}
...

**Comment by Bob-the-Kuhn** [comment]
I'm not able to reproduce your problem.  I just grabbed the latest bugfix and made the changes as above,  I then did the M502, M500 sequence with no complaints.  I then did a couple of M200, M500, M501 cycles without any issues.  Power cycling didn't affect the EEPROM contents (same CRC)..  

Please post your config files & I'll try again.

This problem may have been fixed.  A couple of days ago I couldn't drop a new BIN file onto the USB mass storage window and get it to load into FLASH.  Today all is well.

This is on a Win10 machine.

**Comment by As3uS** [comment]
In my case, when the printer was connected on usb, windows10 can't read the SD, 
A window opened but said unable open, unable to mount. After many change the best result was "drive need to be formatted" when plugged the printer.

it's seems it's similar problem with you @Bob-the-Kuhn. Windows can't access sd after boot, i will try download the last last last build tonight and see if the sd card mount correctly on windows.

**Comment by chrisjenda** [comment]
I have tried with the latest commit and the problem still persists,  I have tried multiple SD cards and also with different types.  I have provided the config files for which I have used during these tests.
https://ufile.io/pwh1n

This is the log created from issuing the following commands (M502, M500, M501) in that order.

11:27:28.540 : echo:Hardcoded Default Settings Loaded
11:27:32.940 : write_data(100,268468032,4...)
11:27:32.940 : f_lseek()=9
...
11:27:32.956 : f_lseek()=9
11:27:36.186 : read_data(100,268468028,4...)
11:27:36.187 : f_lseek()=9
11:27:36.187 : read_data(100,268468018,2...)
11:27:36.187 : f_lseek()=9
11:27:36.187 : echo:EEPROM version mismatch (EEPROM=? Marlin=V52)
11:27:36.187 : echo:Hardcoded Default Settings Loaded

**Comment by p3p** [comment]
I'm afraid I can't reproduce this with any of my sdcards by using fresh clone of bugfix-2.0.x with your config files applied, I presume you can access the USB Mass Storage device to flash new firmware?, (so the cards are working) is the eeprom.dat file ever created?

**Comment by As3uS** [comment]
It's possible that issue was caused by FullGraphic LCD ?
This LCD screen can't provide second SD card access, EXP port pin use same canal from microSD, conflict ? 
@p3p what lcd have you ?

**Comment by p3p** [comment]
I use a `REPRAP_DISCOUNT_FULL_GRAPHIC_SMART_CONTROLLER`, The onboard sdcard is used for firmware flashing and the eeprom data and is completely isolated from other spi communications, it cannot currently be used by Marlin for gcode files, the sdcard on the controller can be used as it normally would be.

**Comment by As3uS** [comment]
And no i can't access to mass storage, when i plug the printer, windows display this popup
![sans titre](https://user-images.githubusercontent.com/34066941/37427450-d202fa8c-27c9-11e8-995e-5f81dc256884.png)
Maybe smoothiedriver ? But no issue in peripherals

**Comment by p3p** [comment]
@As3uS In that case are you running the newest bugfix-2.0.x, your issue may be because of a watchdog timeout, this was already patched.

**Comment by As3uS** [comment]
i just dowload last 2.0.X bugfix +u8glib  same issue...
What commit/issue i should read ?
Can you give us your version archive for test ?

Sorry for spam Question and thank again for your hard work

**Comment by chrisjenda** [comment]
@p3p the dat file is not ever getting created with the latest commit,  I have checked commit 1746a7352efb51d44d47ba5e1deb669fa2b2269f and the EEPROM functions normally.  I suspect something from eeprom v48 to 52 has caused the problem.

**Comment by p3p** [comment]
@chrisjenda I wish I could reproduce this so I had something to debug, but I cloned bugfix-2.0.x, applied your configs, built and flashed, everything worked as expected. I'l check again but I atm I don't see a problem in the software.

@As3uS I don't have a version, I always test with a clean copy of bugfix-2.0.x, just applying any supplied configs, (being why they are a required part of the issue template)

**Comment by Bob-the-Kuhn** [comment]
I get those same errors if I remove the SD card from the RE_ARM board.  It doesn't matter if there is an  SD card is in the LCD controller or not.

If I remember correctly there is a 32G limit on the volume size for the SD card.  I had to format my 64G card as a single 32G volume before it worked.

**Comment by chrisjenda** [comment]
I'm at a loss here, the only thing that I can think of is that I had to flash a replacement bootloader to the Re-Arm shortly after I received it as it shorted out causing the bootloader to become corrupted.  I could not find the original bootloader nor could I get it from pannutech so I found that it must just be the same bootloader for the LPC17XX so I downloaded the latest dev version of the DFU bootloader and flashed it.  one of you with the re-arm would want to download your bootloader with flash magic and upload it for me, would you?

**Comment by Bob-the-Kuhn** [comment]
Here's a link to the [image of the FLASH](https://www.dropbox.com/s/7l7ku32lfrb5igv/LPC1768_image.zip?dl=0) in my Re_ARM.

It's a binary file for 0 - 0x0007 FFFF.

I don't think the bootloader is the problem.  My understanding is that all of the LP1768 FLASH is written when you upload an image via the SD card on the RE-ARM.  Well, not all, just the part that's actually used.

There isn't a bootloader in FLASH like there is on the AVR chips.  There is a bootloader ROM within the LPC1768 that actually does the writing to FLASH.  If there is valid user code in FLASH on power up or reset then control is passed to the user code and it's the user code that interacts with the boot ROM to download a new image.  If the user code is invalid then the boot ROM is in control and it looks for commands via serial port 0.

**Comment by As3uS** [comment]
@p3p , i understand thank, i will give you my MKS configuration tonight.

**Comment by p3p** [comment]
@Bob-the-Kuhn There is the smoothieware bootloader in the flash, it uses the first 16KB. When turned on it looks for firmware.bin and flashes it, offset correctly.

@chrisjenda As long as it actually manages to flash the new firmware I don't see the bootloader being the issue, does the firmware.bin file get renamed to firmware.cur?, and can you confirm build date shown at boot (you will probably need to use the hardware serial port to see it, USB takes too long to initialise and connect)

**Comment by Bob-the-Kuhn** [comment]
~Chris - does the Smoothieware bootloader get overwritten when firmware.bin is loaded?~

Never mind ... just realized what **offset correctly** meant.

**Comment by p3p** [comment]
No, it puts firmware.bin into flash offset by 16KB, in the linker script we set the flash origin for Marlin to 16KB

(should remember to refresh the page before replying)

**Comment by As3uS** [comment]
@p3p I join you my configuration files used with the last marlin 2.0.x.
Now, the SD card Mount again, but now with needed formating windows popup. Firmware.bin is correctly rename on first boot.
[Config-Marlin.zip](https://github.com/MarlinFirmware/Marlin/files/1816508/Config-Marlin.zip)

**Comment by Bob-the-Kuhn** [comment]
Are you putting your SD card into your PC to download the firmware.bin file to it?

On my Win10 PC when I power up my Re_ARM, the first popup says that there's a problem with the drive but then up pops the explorer window for the drive.  I can then copy my firmware.bin file to the SD card via the explorer window.

If Windows isn't popping up the explorer window then there's probably a driver problem.  Win10 is supposed to automatically install the correct driver but I remember problems in that area when I first started using RE_ARM.  Take a look at the [Smoothieware Windows driver page](http://smoothieware.org/windows-drivers) for help on this.

**Comment by Bob-the-Kuhn** [comment]
@As3uS - I just compiled your files & uploaded.  Windows popped up the explorer window as usual.

**Comment by As3uS** [comment]
![sans titre](https://user-images.githubusercontent.com/34066941/37485063-ac241866-288a-11e8-927e-9af2dd56fa52.png)
@Bob-the-Kuhn thank for your test.
The smoothiedriver is okay, sdcard mount correctly directly on the computer.

I don't understand ... Will try another computer.
And flash the Smoothieware firm saw if sd mount.

**Comment by As3uS** [comment]
Just test with the smoothieware firmware the SD mount correctly by usb storage mass

**Comment by Bob-the-Kuhn** [comment]
@chrisjenda - you'll need to go through the serial 0 port to copy my image into your LPC1768.  BIN files don't contain absolute addresses so putting my image on the SD card & rebooting will just crash your controller.

If I remember correctly something like an FTDI cable is needed to make use of the serial 0 port.

**Comment by Bob-the-Kuhn** [comment]
@As3uS - does that mean everything is working for you?

**Comment by As3uS** [comment]
Edited:

@Bob-the-Kuhn nope sir.
-> My computer / marlin -> No mounting SD
-> My computer / Smoothie firmware -> sd mount correcty
-> Other W10 computer (i stole my wife's laptop ^^) / Marlin ->No mounting SD

@Bob-the-Kuhn @p3p thank you for your help and patience

**Comment by Bob-the-Kuhn** [comment]
Here's what my Win10 device manager says.  Notice that it doesn't mention the Smoothie drive on the com port.

Maybe try the following:
1. uninstall the com port with the smoothie driver on it
2. unplug the RE_ARM
3. reboot
4. plug the RE_ARM back in.
5. see what Windows installs

Or just do a driver update and select the same one as on my PC or on your wife's laptop.  Or just steal her laptop.

![disk drive](https://user-images.githubusercontent.com/20692583/37486763-7476ff1e-285d-11e8-83e5-2d7efbfc46ca.JPG)
![com 3](https://user-images.githubusercontent.com/20692583/37486770-78afe1b8-285d-11e8-9211-c0e2e18ecd75.JPG)
![composite](https://user-images.githubusercontent.com/20692583/37486774-7c04bc1c-285d-11e8-932f-a5c1ca4395af.JPG)
![usb mass storage](https://user-images.githubusercontent.com/20692583/37486781-8002804c-285d-11e8-8605-544656b620f3.JPG)

**Comment by As3uS** [comment]
@Bob-the-Kuhn  i have the same issue of this thread, but i'am on MKS Sbase. 
I edited my previous post because i don't saw but when i swaped my sd card to put the marlin and test it on my wife's computer, board never reflash the marlin firm, so the sd have mount yes but with smoothie again 
Don"t worry i will abandonned, my printer working well, i will flashed if i have other modification and forget m500.

i prefere flashing if i have a modification than use smoothie ^^

**Comment by Bobsy5361** [comment]
![2130](https://user-images.githubusercontent.com/30444509/37487749-6fb85cd4-288a-11e8-9a8b-8db5272a3627.JPG)
[New folder.zip](https://github.com/MarlinFirmware/Marlin/files/1816895/New.folder.zip)

**Comment by Bob-the-Kuhn** [comment]
Sorry - Marlin uses the same code for all the LPC176x based boards.  Sometimes I forget which motherboard is being used by which person.

Here's more details on the disk drive.

![image](https://user-images.githubusercontent.com/20692583/37487920-085c672a-2861-11e8-8f5f-a26edaa9fb53.png)

Here's my files as shown in the snapshot.
[disk.zip](https://github.com/MarlinFirmware/Marlin/files/1816918/disk.zip)

**Comment by As3uS** [comment]
Ok my bad ;) so okay for the storage driver, but same issue with 2 computer, one with driver other without.
Think it's not the drivers ?

**Comment by chrisjenda** [comment]
I will flash the bootloader tonight and try again.  It's very hard for me to work on this issue currently as my main computer's motherboard has decided to take a turn for the worst.

**Comment by As3uS** [comment]
Hi there,
@Bob-the-Kuhn @p3p i remove my FullGraphic screen and pluged the usb on my computer and what ? The SD card mounted correctly i can perform a M500 with ponterface. And file eeprom.data write correctly also.

**Comment by Bob-the-Kuhn** [comment]
Are you fully functional now?

**Comment by As3uS** [comment]
Hi bob, i bought a MKS TFT. 
Now it's fully fonctionnal with a MKS TFT"3.2 Screen but no with the reprap full graphic.
It's ok for me. Thank :)

**Comment by chrisjenda** [comment]
Looks like I will be down for another 2 weeks due to the computer problems I am having.  I'm currently using a 10 year old labtop with a 1.3ghz processor while waiting for my Main PC MB to be finish RMA, so bear with me.. lol  I guess you can close this issue and pehaps we could re-open it when I can do more testing, but for now, I am unable to test any suggestions.

**Comment by Nuttavoot** [comment]
With the lastest build, I also get "EEPROM datasize error" when issue M500, M501, M504 on RE-ARM board and no file eeprom.data was created on the SD card.
