### ISSUE TITLE
open failed, File: XXX

### ISSUE THREAD

**Issue by cuthulino** [MarlinFirmware/Marlin#1080]
Hey community....

I just changed my marlin version and my Repetier-Host version to the newest.

Before, it was no Problem to print from the SD Card
but now nothing is working and i dont know why!?

SD Support ist active, Files are listed but if i want to start a print, 
i get this messages:
"echo:Now fresh file: xxx~1.gco"
"open failed, File XXX~1.gco"

I tried already with .gco and .gcode
with long and short names but nothing worked....
SD is FAT.

I dont know what the problem is...

Can someone help me with this?
Im just frustrated :(

//Informations:
I use Ramps 1.4 with SDRamps
Slic3r v. 1.17
Repetier-Host 1.0.4

**Comment by c11gott** [comment]
Hi, I use the Repetier-Host Version V1.0.2 and had the message:
"open failed, File XXX.gco .".
Note that there is a space between the extention "gco" and following dot! So I guess that the new Repetier-Host sends a ending space after the filename!
I have fixed my local Merlin Firmware in the method make83Name() implemented in SdBaseFile.cpp with a simple trim space loop after while(i < 11 )....

```
//------------------------------------------------------------------------------
// format directory name field from a 8.3 name string
bool SdBaseFile::make83Name(const char* str, uint8_t* name, const char** ptr) {
  uint8_t c;
  uint8_t n = 7;  // max index for part before dot
  uint8_t i = 0;
  // blank fill name and extension
  while (i < 11) name[i++] = ' ';

  // trim ending spaces (bug in Repetier-Host?)
  size_t len = strlen(str);
  for( ; len > 0; --len) {
    if(str[len - 1] == ' ') {
      ((char&) str[len - 1]) = '\0';
    } else {
      // else nothing to do.
      break;
    }
  }

  i = 0;
```

Hope I can help you with this solution...

**Comment by GabeHC** [comment]
It's never been fixed, not even with V1.0.3

**Comment by thinkyhead** [comment]
@GabeHC See if this fixes the issue: Find the line in `process_next_command` which reads…

```
  if (starpos) *starpos = '\0';
```

…and replace it with…

```
  if (starpos) while (*starpos == ' ' || *starpos == '*') *starpos-- = '\0';
```

PR to fix the issue: #2409

**Comment by GabeHC** [comment]
Yes! it fixes it simple and easy.

**Comment by dteeter** [comment]
Just verified that this bug is still there, clear as day, in build 1.0.2.

**Comment by Wackerbarth** [comment]
This was corrected in our development branch. I do not expect it to be back-ported to the 1.0.x branch.

**Comment by dteeter** [comment]
For those folks who print primarily from an SD card (who may find this release unusable), do you recommend that they try the dev branch?

**Comment by tonnico** [comment]
No, but the Dev will be later the release. This is the intention.
