### ISSUE TITLE
EEPROM cause extruder problem.

### ISSUE THREAD

**Issue by HackerTon** [MarlinFirmware/Marlin#1378]
When EEPROM is enable, extruder stepper is not able to turn at any condition.

**Comment by arno-millenaar** [comment]
Confirmed this maybe a problem.  See my comment at https://github.com/MarlinFirmware/Marlin/issues/1209

EDIT:  No its not a problem, see below thread. Problem solved.

**Comment by nophead** [comment]
If you download new firmware with a different EEPROM layout you will get garbage values until you do  M502: revert to the default "factory settings" to re initialise it. There is a version number in the EEPROM that can be changed if the layout changes but nobody does and having conditional variables will cause layout changes anyway when options are changed.

**Comment by arno-millenaar** [comment]
@nophead 
thanks a million as indeed this was my bad. I should have known as i typically always issue a M502 followed by a M500 when loading new firmware.  For whatever reason I was convinced I had done this, however I just tested again, after a M502/M500 combo and now its working fine. With EEPROM and CHITCHAT enabled, extruder etc is working.

Thanks again for your feedback as this problem is solved and confirmed after testing.

**Comment by HackerTon** [comment]
I did use M502 but the extruder is still not working.
My setup:Megatronics 2.0, DRV8825 in 16 microstepping, ATX power supply, RRD Full Graphics LCD.

Thanks for you collaboration.

**Comment by arno-millenaar** [comment]
After using M502, you should also issue the M500 command. Did you try that as well ?

At least I now seem to have working firmware, including working extruders, having pulled the dev branch (993bcd370) this morning.

**Comment by HackerTon** [comment]
Yes, I did what you told me to.

**Comment by arno-millenaar** [comment]
Just to exclude everything else have you re-loaded your previous (working) firmware, just to make sure its caused by this specific version ?  As far as I can tell from the responses from the other Testers they all seem to have working machines with this specific dev version.  Also try disabling your LCD function, just to make sure their is no relationship as I don't have your type of LCD module.

**Comment by HackerTon** [comment]
Finally, I got it working only by using M502 alone. After restart, problem occur again and also M502/M500 combo is not working. No RRD Full Graphics LCD.

**Comment by arno-millenaar** [comment]
After issuing M502/M500 and give it a hard reset do you read back the expected values issuing M503 ?
At least it seems you are heading in a similar direction that 'solved' my initial problem.

EDIT: also try M501 to read back from EEPROM.

**Comment by HackerTon** [comment]
This is what i got after issuiing M503
(01:41:19.435 : echo:Steps per unit:
01:41:19.435 : echo:  M92 X78.74 Y78.74 Z533.33 E836.00
01:41:19.435 : echo:Maximum feedrates (mm/s):
01:41:19.435 : echo:  M203 X500.00 Y500.00 Z5.00 E25.00
01:41:19.435 : echo:Maximum Acceleration (mm/s2):
01:41:19.435 : echo:  M201 X9000 Y9000 Z100 E10000
01:41:19.435 : echo:Acceleration: S=acceleration, T=retract acceleration
01:41:19.435 : echo:  M204 S3000.00 T3000.00
01:41:19.436 : echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
01:41:19.436 : echo:  M205 S0.00 T0.00 B20000 X20.00 Z0.40 E5.00
01:41:19.436 : echo:Home offset (mm):
01:41:19.436 : echo:  M206 X0.00 Y0.00 Z0.00
01:41:19.436 : echo:PID settings:
01:41:19.436 : echo:   M301 P22.20 I1.08 D114.00
)

After 
(01:42:29.296 : echo:Stored settings retrieved
01:42:29.296 : echo:Steps per unit:
01:42:29.296 : echo:  M92 X78.74 Y78.74 Z533.33 E836.00
01:42:29.296 : echo:Maximum feedrates (mm/s):
01:42:29.296 : echo:  M203 X500.00 Y500.00 Z5.00 E25.00
01:42:29.296 : echo:Maximum Acceleration (mm/s2):
01:42:29.296 : echo:  M201 X9000 Y9000 Z100 E10000
01:42:29.296 : echo:Acceleration: S=acceleration, T=retract acceleration
01:42:29.296 : echo:  M204 S3000.00 T3000.00
01:42:29.296 : echo:Advanced variables: S=Min feedrate (mm/s), T=Min travel feedrate (mm/s), B=minimum segment time (ms), X=maximum XY jerk (mm/s),  Z=maximum Z jerk (mm/s),  E=maximum E jerk (mm/s)
01:42:29.296 : echo:  M205 S0.00 T0.00 B20000 X20.00 Z0.40 E5.00
01:42:29.296 : echo:Home offset (mm):
01:42:29.296 : echo:  M206 X0.00 Y0.00 Z0.00
01:42:29.296 : echo:PID settings:
01:42:29.296 : echo:   M301 P22.20 I1.08 D114.00
)

After all the testing, not working. Curious.

**Comment by thinkyhead** [comment]
@nophead @arno-millenaar I'm seeing a few messages indicating confusion about this. It seems like a good idea to add code that checks the version number in the EEPROM and resets the EEPROM when it's not the current version – perhaps with some kind of feedback to the user. If an issue hasn't been added for this, I will toss it into the mix now.

**Comment by nophead** [comment]
As far as I can see it already does that but nobody changes the version number.

**Comment by thinkyhead** [comment]
Hmm... Maybe there could be a failsafe that checks against the _size_ of the EEPROM data...? Since users might enable or disable features that change the EEPROM storage also. Any other ideas bout how it could automatically catch this?

**Comment by nophead** [comment]
daid's suggestion of a magic value at the end should catch size changes.

At the moment the size isn't easy to calculate as each variable is written separately. A better scheme is to make a structure with the layout in it. I think that would save a lot of code and you can then take its size.

**Comment by thinkyhead** [comment]
@nophead +1 on the struct idea.

**Comment by thinkyhead** [comment]
#1428 should make the EEPROM consistent regardless of enabled features.

**Comment by tadawson** [comment]
Try `M200 D0` . . . I have found a problem (#2490) where once volumetric extrusion gets set, the code won't allow you to disable it - the values hang in prom, and it comes back on every reset . . . if this does the trick, likely we are having the same problem.

**Comment by thinkyhead** [comment]
@tadawson So far I don't see the behavior, at least not reflected in the current settings.

Here's the procedure I used to test:
- `M200 D1.69` to set `volumetric_enabled`, the `filament_size` for the `active_extruder`, and update all `volumetric_multiplier` values.
- `M503` to see the current state. It replies `M200 D1.69`.
- `M500` to save the settings.
- Power down and reboot. EEPROM restored, says `M200 D1.69` (correct).
- `M200 D0` to disable `volumetric_enabled` and set all `volumetric_multiplier` values to `1.0`.
- `M503` to see the current state. It replies: `Filament settings: Disabled`.
- `M500` to save current state (disabled).
- Power down and reboot. EEPROM restored, says `Filament settings: Disabled` (correct).

Do you see the same output as I do?
Is the volumetric behavior still happening when it claims (via `M503`) to be turned off?

**Comment by tadawson** [comment]
The  main artifact I see is that my extruder volume goes insane unless I correct as described. I also feel a little less nuts, since I had the file name written both ways as I updated my bug, from  two different systems, with two separate git images . . . the quickee I didn't get switched to Development was last, hence the filename . . . . I thought I was going nuts!

I don't think M503 base output is accurate, since one of the first things I did before I found this was to capture the output of M503 when good and when bad, and noted no difference. I honestly think that while volumetric_enabled is being set correctly, and which determines the output of M503, the values are still being applied.

As I recall, M503 S0, to show just the gcode did show the issue . . .

I'll retest tomorrow. . . my  memory is that I see what you see except the last, I would still see M200 D1.69

My codebase might be a week or so behind dev - this is a port to Due, but the owner brings in updates often, and on comparison, I did not see any diffs in Marlin_main.cpp or configuration_store.cpp.
- Tim

On July 23, 2015 9:17:33 PM CDT, Scott Lahteine notifications@github.com wrote:

> @tadawson So far I don't see the behavior, at least not reflected in
> the current settings.
> 
> Here's the procedure I used to test:
> - `M200 D1.69` to set `volumetric_enabled`, the `filament_size` for the
>   `active_extruder`, and update all `volumetric_multiplier` values.
> - `M503` to see the current state. It replies `M200 D1.69`.
> - `M500` to save the settings.
> - Power down and reboot. EEPROM restored, says `M200 D1.69` (correct).
> - `M200 D0` to disable `volumetric_enabled` and set all
>   `volumetric_multiplier` values to `1.0`.
> - `M503` to see the current state. It replies: `Filament settings:
>   Disabled`.
> - `M500` to save current state (disabled).
> - Power down and reboot. EEPROM restored, says `Filament settings:
>   Disabled` (correct).
> 
> Do you see the same output as I do?
> Is the volumetric behavior still happening when it claims (via `M503`)
> to be turned off?
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/MarlinFirmware/Marlin/issues/1378#issuecomment-124293594

## 

Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by thinkyhead** [comment]
> I don't think M503 base output is accurate

It's accurate concerning the values that it displays. But it doesn't reveal the values that are used by the planner, specifically the `volumetric_multiplier[]` array. If these values are set to anything other than 1.0 then you will get volumetric behavior in the planner.

The `volumetric_multiplier` values default to 1.0 on boot, and are recalculated only on these occasions:
- Restore with `M501`. All recalculated if `volumetric_enabled`. Otherwise all set to 1.0.
- Reset with `M502`. Always set to 1.0 by this.
- Any `M200 Dn` command. All recalculated if `volumetric_enabled`. Otherwise all set to 1.0.
- Edit with the LCD Menu. All recalculated if `volumetric_enabled`. Otherwise all set to 1.0.

**Comment by tadawson** [comment]
My issue is resolved - see #2490 . . . I got hit with a single character error in the PIDTEMP EEPROM read code that had already been corrected by commits past mine.  Details in #2490 . . .

**Comment by tadawson** [comment]
Submitted to wrong issue . . .
