### ISSUE TITLE
[BUG] BL Touch Probing failure at 8th point

### ISSUE THREAD

**Issue by hussainsail2002** [MarlinFirmware/Marlin#15237]
### Description

While running G29 with the bltouch, the probe seems to always fail at the 8th point, the bed would barely touch the probe and drop down saying that the probing has failed. I also used the feature to recover and retry up to 3 attempts but all fail. Occasionally though it succeeds and I start my print.

Once my print has started the right hand side front corner always seems squished compared to the left hand side back corner. If offset is changed to accommodate the front left corner then the other corner tends to warp.   

### Steps to Reproduce

1. Use the latest bugfix firmware - I used the one on 7th Sept 2019
2. Install a bltouch
3. Print a full bed size print

**Expected behavior:**

I expected the bltouch to probe reliable without failing, also would like if the leveling is perfectly even and the print does not squish on one side and lift on the other

**Actual behavior:** 

I have to keep restarting the machine hoping the leveling would succeed and once that's done, i need to accept that the print will be a bit squished 

#### Additional Information

I have read that the uneven leveling may be due to the fact that the X axis is twisted, but if it is so shouldn't it be twisted for all points ? I am assuming that the bltouch works on contact force, so if for all points the same twist is maintained then that should not really be a problem.

I have a custom built core XY machine with the Z axis moving up and down

**Comment by boelle** [comment]
please attach your 2 config files as a zip file, just as the issue template told you to

**Comment by hussainsail2002** [comment]
[config_files.zip](https://github.com/MarlinFirmware/Marlin/files/3608571/config_files.zip)

Hi,
Sorry I forgot to add them, attached to this comment

Thanks
Hussain

**Comment by tvixen** [comment]
Are you using Pronterface to do the commands or LCD display

**Comment by hussainsail2002** [comment]
@tvixen Thanks for the reply,

I issued the command by adding G29 after G28 in my start Gcode.

**Comment by tvixen** [comment]
Hmm try to do the commands in Pronterface. It's easier to debug.
It sounds like your missing points in your mesh, is because of the mesh size.
Remember also to add #define RESTORE_LEVELING_AFTER_G28 to your code.

Try reading this: http://marlinfw.org/docs/gcode/G029-mbl.html
This will give your the basic knowledge.

**Comment by hussainsail2002** [comment]
I will try pronterface

My mesh has only 9 points ! and it fails at the 8th one

you don't need #define RESTORE_LEVELING_AFTER_G28  if you do G29 after G28 in start G code.

The bltouch completes it successful sometimes and fails sometimes, this is creating a reliability issue

**Comment by tvixen** [comment]
Is it a clone...they are notorious known for their reliability 
which version af bltouch (1.0, 2.0, 2.2, 3.0, 3.1,)

**Comment by lococnc** [comment]
This is a WIDELY reported issue with BLTouch probes v3 and v3.1 Seems the older V2 and earlier works. Mine has stabilized by supplying an external 5v and a 1000uf cap to the E0Stop 5v and gnd pins. Also works when USB WITH power is plugged in.

**Comment by Roxy-3D** [comment]
> Is it a clone...they are notorious known for their reliability

Let's do a quick sanity check.    What does an M48 P50 do?
(I wouldn't be surprised if that crashes the nozzle into the bed if you do it a few times.)

**Comment by hussainsail2002** [comment]
@tvixen Its the original bltouch V2.2 , I had written to paris about this as well but was not able to get clear feed back, I had bought 10 Bltouch's and this issue has shown up on atleast 4 out 5 of these bltouch's that I have tested.

@lococnc I read many of the other issues that said V3 has issues , but none mentioned V2.2

@Roxy-3D I will check with M48 P50, I am assuming that to do this I need to activate the following:

//#define Z_MIN_PROBE_REPEATABILITY_TEST

Thanks

**Comment by hussainsail2002** [comment]
I use an MKS Gen V1.4 board, and I have wired it as given at the bltouch website

**Comment by Roxy-3D** [comment]
Is everything working with the new wiring?    Or do you still have the problem?

**Comment by Aurawin** [comment]
If not, you may want to increase Z_PROBE_LOW_POINT to perhaps -4 or -5.  Mine *was* -2 until I got problems like that.  I use BI_LINEAR tough.

**Comment by hussainsail2002** [comment]
Hi, 

sorry for my delay in replying

So I managed to fix the issue but I do not understand why it happened

The issue was that the bl touch would constantly fail to probe the point 6,7 or 8. I realized that max failure was at point 7 but occasionally it would fail at 6 and 8 as well.

These 3 points happen to be at the left hand side rear corner of the bed. I noticed that the bed moves up (I have the bed on Z axis) only a certain height until it triggers the probe, if it does not hit the probe at the height it has moved up it will fail.

I loosened the tension on the spring  at the rear left corner to lift the bed up, once I did that It stopped failing

I use Linear bed leveling.

Though the issue has been solved , i hope someone can explain the reason for this phenomenon.

Thanks to everybody for their valuable contributions.
Hussain

**Comment by boelle** [comment]
fixed, closing

**Comment by Hukuma1** [comment]
Getting the same thing. It seems to fail right after a move to a different row. It's happened a few times, and always right after a move to next row. BL Touch 2.2 as well. Because it sometimes passes without failure, I'm guessing some sort of vibration is the cause of error?

**Comment by Aurawin** [comment]
The Z_PROBE_LOW_POINT in Configuration.h specifies the tolerance of bed leveling and Z-axis alignments.  If the bed has to move from know 0 to 5 up above then as soon as it hits 5 it will stop with an error.  If this value is too low you will find the probe failure.  It can occur if one of the corners are low especially if you have not done a G34.  

I realize large values negative can cause mashing - I installed manual endstops on my lead screws to solve that.

My last point is that when you see probe error or stalls it is rarely a "probe" failure in respect to a hardware issue.  Ie:

If you examine the output of the G29 command you will see a table of values. If your values exceed or approach Z_PROBE_LOW_POINT you will certainly get probe failure.

Unless there is a glitch in your hardware -

This is the expected behavior.

**Comment by Plselvig** [comment]
I am getting this same issue I have an Ender5 with a SKR v1.4Turbo with BLTouch 3.1.  I set the Z_PROBE_LOW_POINT to -4 and the four corners are a high as they go.  But I still get the probing failed after the 7th probe.  Not sure what else to check.

**Comment by thinkyhead** [comment]
@Plselvig — Please open a new issue if you believe there is a bug. You will be given instructions on how to gather extra logging which will look like this:

"
Whenever there are homing or leveling issues, we ask everyone to follow a standard procedure to gather more information so that we're not just taking stabs in the dark. Here is the boilerplate:

- Download Marlin `bugfix-2.0.x` to test with the latest code.
- Enable `DEBUG_LEVELING_FEATURE` and `M114_DETAIL` and re-flash the firmware.
- Connect to your printer from host software such as Cura, Printrun or Repetier Host.
- Send `M502` and `M500` to ensure your Configurations are applied.
- Issue the command `M111 S247` to enable maximum logging.
- Perform a `G28` to do your standard homing procedure.
- Do a `G29` to probe the bed. This will also enable bed leveling.
- Copy the log output into a **.TXT file** and attach it to your next reply.

From these logs we should hopefully get a better idea of what's going on with your machine.
"

**Comment by BlueWebCoder** [comment]
Hi,
I'm getting the same issue.
Probing stop after 4 points on a 5x5 grid. here is my .TXT file attached.
If you have an idea ...
Some errors are printed like > grid spacing issue or > probe_position_lf issue. Those errors are my debug of g29.cpp Marlin file. They trigger why i get a reset_bed_level.
I add thoses lines to the G29.cpp file : 

      if (gridSpacing != bilinear_grid_spacing || probe_position_lf != bilinear_start) {
        // Reset grid to 0.0 or "not probed". (Also disables ABL)
        if (gridSpacing != bilinear_grid_spacing){   // added
          if (DEBUGGING(LEVELING)) DEBUG_ECHOLNPGM("> grid spacing issue");  // added
        }
        if (probe_position_lf != bilinear_start){  // added
          if (DEBUGGING(LEVELING)) DEBUG_ECHOLNPGM("> probe_position_lf issue"); // added
        }
        reset_bed_level();
        // Initialize a grid with the given dimensions
        bilinear_grid_spacing = gridSpacing.asInt();
        bilinear_start = probe_position_lf;

        // Can't re-enable (on error) until the new grid is written
        abl_should_enable = false;
      }

[file.txt](https://github.com/MarlinFirmware/Marlin/files/5012700/file.txt)
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/5012923/Config.zip)


Thanks
