### ISSUE TITLE
[BUG] Octoprint can't find interface SKR mini

### ISSUE THREAD

**Issue by Udo-Nbg** [MarlinFirmware/Marlin#16387]
[Marlin_2.0.1_configs.zip](https://github.com/MarlinFirmware/Marlin/files/4010879/Marlin_2.0.1_configs.zip)

SKR mini V 1.1 connection problem:
Marlin 2.0.1 (2019-12-28)
I have the problem that Octoprint (octopi-buster-lite-0.17.0 @ Pi4) cannot find the board / interface.
The connection works perfectly under Windows 10.
Apparently a firmware problem / USB driver / USB driver signature that occurs with Octoprint.
The interface/board is only recognized very rarely, mostly not.

Tested on two different SKR mini V1.1:
one mounted on Printer, 24V supply powered, with 12864 Display, tmc2208 standalone
other direct connected / USB-powered / no Display, no Motordrivers attached, nothing else connected (board only)

Also with four (4) different USB-Cables tested.

**Comment by boelle** [comment]
Configurations, please
Please ZIP up your `Configuration.h` and `Configuration_adv.h` files (as
requested in the Issue template) and drop them into your next reply.
We'll check them over and see if anything is amiss.

**Comment by Udo-Nbg** [comment]
Sorry, 
done.
[Marlin_2.0.1_configs.zip](https://github.com/MarlinFirmware/Marlin/files/4010901/Marlin_2.0.1_configs.zip)

**Comment by Lord-Quake** [comment]
Try setting the following in configuration.h:

`#define SERIAL_PORT 2`
and
`#define SERIAL_PORT_2 -1`

**Comment by Udo-Nbg** [comment]
1st happy new Year ;-)

But sorry, that did not solve my problem.

Issues are exactly the same.
I can connect an control with Windows (10) succesfully
But there ist no device found on the Pi4 with octopi

Here are the octopi messages:
`Changing monitoring state from "Offline" to "Detecting serial port"
Serial port list: []
Changing monitoring state from "Detecting serial port" to "Error: Failed to autodetect serial port, please set it manually."
Failed to autodetect serial port, please set it manually.`

I rebuild the soure completly new, and attched the configuration.h again...

[Marlin_2-0-1.zip](https://github.com/MarlinFirmware/Marlin/files/4014082/Marlin_2-0-1.zip)

**Comment by boelle** [comment]
check what serial ports or usb ports that are on the pi when the printer is connected and when not connected

make sure the pi has any needed drivers, this can be (and most likely will be) different than on windoze

google if other have the same problem on the pi

**Comment by boelle** [comment]
@Udo-Nbg still the same issue?
have you tried with bugfix 2.0.x ? 2.0.1 is just a frozen copy of 2.0.x

**Comment by Udo-Nbg** [comment]
Yes still the same issue,
Windows easily recognizes and uses the driver
Linux (octoprint) doesn't even find an interface.

and I wasn't familiar with the frozen verion.
I will try the current bugfix 2.0.x shortly.

Thank you

**Comment by boelle** [comment]
does linux have all needed drivers installed?

**Comment by Udo-Nbg** [comment]
which driver i have to install?
chipset oder driver source please

i can not find any source for maple Drv-USB driver for linux
i can not find any easy, simple instruction...

btw. If i connect a FT232RL USB Serial Stick, this one will instant recognized

AND i compiled today wit a fresh download of Marlin bugfix 2.0.x and still the same issue.

**Comment by sam2b** [comment]
@Udo-Nbg what com port are you specifying in OctoPrint? For example, mine is /dev/ttyACM0
(ttyACM zero)

To confirm, have you compared the /dev directory listing *without* the printer usb cable connected to the Raspberry Pi vs. when connected? If not, what is your comparison result, please?

**Comment by Udo-Nbg** [comment]
@sam2b i can NOT select any port there is nothing in octoprint
because NOTHING will recognized :-(

in windows works all fine, driver (ComPort) and controlling.

**Comment by sam2b** [comment]
@Udo-Nbg I'm asking for you to compare the /dev directory listing in Linux without the printer usb cable connected to the Raspberry Pi vs. when connected. What is your comparison result, please?

**Comment by Udo-Nbg** [comment]
I replied: "because NOTHING is recognized"
I mean that nothing is recognized also in the /dev folder no change.

I tested with an ftdi ft232 usb-serial adapter, which is recognized immediately and also appears and disappears in the /dev folder when I plug in or unplug it, 
so please don't consider myself stupid

**Comment by boelle** [comment]
so maybe bad hardware since nothing happens?

**Comment by Udo-Nbg** [comment]
That would be logical and also my guess
but how does that explain the correct function under windows 10?

Nevertheless, I ordered two new SKR mini V1.1, one as a replacement and the second as a spare.
But I observe exactly the same behavior on all three boards.

Now you could also consider that the cable could be the cause, I also thought of that and the original cable is actually defective. But I also have this problem with three or four other high quality cables.

Also i read some issues with iterferring power supply.
so i powered one Board only by 5Volt over usb and another with 24V Meanwell Supply and no isolated and isolated (taped) USB Power connector on the cable, but this also not solve the problem.

In the meantime, I've ordered the Lerdge X board that has closed the firmware, but I've had good experiences with Lerdge. By the way, my Lerdge K-Board works great with Octoprint *, so it can't be because of the Raspberry Pi 4 *.

As soon as I have received the Lerdge X, I'll report.

as I have written bevore, in my opinion the firmware or the unavailable driver is the reason for the malfunction.

So I'm not perfect in Linux, but mostly I get things to work with, but this one give me a headache

And the comment "google if other have the same problem on the pi" woud be great but i dont find any, and i seached a lot, but i found only windows solutions, nothing in relation to linux or octoprint,

Maybe there is a reason with the bootoader oder permanent firmware?
i have different ST-Link V2 Adapters to burn it on, if i get the right bootloader an exact instructions how to do that the right way.

**Comment by boelle** [comment]
> but how does that explain the correct function under windows 10?

because win10 prob does at lot in the background automatic without telling, and linux dont do that

just a guess

**Comment by Udo-Nbg** [comment]
:-( that helps me a lot (NOT).

**Comment by boelle** [comment]
i'm just a user like you so dont expect an expert answer

also remember that everyone working on marlin is working for free and you dont pay for it so you cant expect support like on a real product

**Comment by Udo-Nbg** [comment]
Raspberry Pi 4, 4GB supplied with original Raspberry 3A Supply, 
SKR mini V1.1 at USB 2.0 Port, lower left port (black):

`pi@octopi:~ $ ls /dev/tty*
/dev/tty    /dev/tty19  /dev/tty3   /dev/tty40  /dev/tty51  /dev/tty62
/dev/tty0   /dev/tty2   /dev/tty30  /dev/tty41  /dev/tty52  /dev/tty63
/dev/tty1   /dev/tty20  /dev/tty31  /dev/tty42  /dev/tty53  /dev/tty7
/dev/tty10  /dev/tty21  /dev/tty32  /dev/tty43  /dev/tty54  /dev/tty8
/dev/tty11  /dev/tty22  /dev/tty33  /dev/tty44  /dev/tty55  /dev/tty9
/dev/tty12  /dev/tty23  /dev/tty34  /dev/tty45  /dev/tty56  /dev/ttyAMA0
/dev/tty13  /dev/tty24  /dev/tty35  /dev/tty46  /dev/tty57  /dev/ttyprintk
/dev/tty14  /dev/tty25  /dev/tty36  /dev/tty47  /dev/tty58  /dev/ttyS0
/dev/tty15  /dev/tty26  /dev/tty37  /dev/tty48  /dev/tty59
/dev/tty16  /dev/tty27  /dev/tty38  /dev/tty49  /dev/tty6
/dev/tty17  /dev/tty28  /dev/tty39  /dev/tty5   /dev/tty60
/dev/tty18  /dev/tty29  /dev/tty4   /dev/tty50  /dev/tty61`

**Comment by Udo-Nbg** [comment]
OctoPrint version : 1.3.12
OctoPi version    : 0.17.0
------------------------------------------------------------------------------

pi@octopi:~ $ lsusb
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 0403:6001 Future Technology Devices International, Ltd FT232 Serial (UART) IC
Bus 001 Device 002: ID 2109:3431 VIA Labs, Inc. Hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
pi@octopi:~ $
pi@octopi:~ $ ls /dev/serial/by-id/*
/dev/serial/by-id/usb-FTDI_USB_Serial_Converter_FTFLYVHJ-if00-port0



i connected a seperate usb serial interface just for test and it appears as FT232 Serial (UART) IC

**Comment by boelle** [comment]
so either the usb on the board is dead or there are no drivers

**Comment by Udo-Nbg** [comment]
I had a session with a Linux expert yesterday, about 2 hours.

Obviously, the problem is that there are no drivers from ST for Linux, specially for this kind of Processorchip STM32F103RCT6 avaiable.

So it is NOT a problem on Marlin.

Thank you for your patience.

**Comment by boelle** [comment]
No problemo, but a shame that there is no driver
