### ISSUE TITLE
[BUG] Anycubic Kossel Delta Plus, auto calibration fails

### ISSUE THREAD

**Issue by pablopeu** [MarlinFirmware/Marlin#17062]
Printer Anycubic Kossel Delta Plus, type 2 probe, marlin 2.044, modified provided example config.

Modified the bare minimum of the configuration example provided, when I start auto calibration it touches the table twice and fails. 
Using the paper method I entered the proper delta height, and then did the bed leveling with the probe (type 2) which finished successfully, now its printing fine.
So at least for me Marlin 2.044 works fine so far for everything but auto calibration.
Attached are the config files.
Thanks

[Anycubic Kossel Delta Plus Marlin 2.044.zip](https://github.com/MarlinFirmware/Marlin/files/4284152/Anycubic.Kossel.Delta.Plus.Marlin.2.044.zip)

**Comment by sjasonsmith** [comment]
Try with the bugfix-2.0.x branch. Related issues have been fixed since 2.0.4

**Comment by pablopeu** [comment]
Autocalibration worked fine with 2.04bugfix. Attached are the slighltly modified config files.

[Marlin 2.044bugfix 4-3-20.zip](https://github.com/MarlinFirmware/Marlin/files/4290087/Marlin.2.044bugfix.4-3-20.zip)

**Comment by thinkyhead** [comment]
What a difference a half a mm makes!

**Comment by pablopeu** [comment]
well, its not that, after resetting eeprom, doing a full g28>g29>m500 the bed is still not properly level, on the right is higher, on the left is lower, this is clearly seen on prints that cover almost all the delta bed. On the second layer, on the left side looks like a 1st layer and on the right side its as expected.

**Comment by pablopeu** [comment]
![image](https://user-images.githubusercontent.com/25783916/76130061-240b6780-5fe8-11ea-9f08-c622c6f9a874.png)
