### ISSUE TITLE
MKS Robin nano v.2 bootloop

### ISSUE THREAD

**Issue by Malderin** [MarlinFirmware/Marlin#19709]
Marlin 2.0.Bugfix.
After update:
https://github.com/MarlinFirmware/Marlin/pull/19192
the board is rebooted upon loading after the start logo. Next comes the endless reboot (bootloop).
File configuration.h  set parameters:
#define MKS_TS35_V2_0
#define TFT_LVGL_UI

**Comment by tpruvot** [comment]
was due to 0988af453c567fae1796cc821bbc41e930b45836

may have been fixed today with tft refactor commit

**Comment by Malderin** [comment]
Marlin 2.0.7.2 (stable).
File configuration.h set parameters:
#define MKS_TS35_V2_0
#define TFT_LVGL_UI
The board boots, but the color gamut is incorrect. Tried adding parameters:
#define TFT_COLOR TFT_COLOR_RGB
 #define TFT_COLOR TFT_COLOR_BGR
to configuration.h, nothing changes.
See video: [error](https://yadi.sk/d/4D6h30Yrq1nwAg)
My fork with configurations: https://github.com/Malderin/Marlin_2.0.x_official/tree/Marlin2.0.7

**Comment by Malderin** [comment]
after rolling back this commit:
https://github.com/MarlinFirmware/Marlin/commit/fea0db47d
board started normally.

**Comment by rhapsodyv** [comment]
Please try #19710 . It's fixed now.

Thanks!

**Comment by Malderin** [comment]
> Please try #19710 . It's fixed now.
> 
> Thanks!

1. Marlin 2.0.7.2 problem solved
2. Marlin 2.0.bugfix, the color scheme has become normal (visible on the splash screen), but the bootloop is still

**Comment by rhapsodyv** [comment]
What are your configs?

You need to disable "TOUCH_SCREEN" when using LVGL.

**Comment by Malderin** [comment]
> What are your configs?
> 
> You need to disable "TOUCH_SCREEN" when using LVGL.

Found the reason. If #define USE_WATCHDOG is uncommented in Configuration_adv.h then the board goes into reboot.

My configurations:
[Conf.zip](https://github.com/MarlinFirmware/Marlin/files/5373397/Conf.zip)
or in my fork:
https://github.com/Malderin/Marlin_2.0.x_official/tree/Marlin2.0.7_bugfix

**Comment by rhapsodyv** [comment]
The watchdog problem is fixed here: https://github.com/MarlinFirmware/Marlin/pull/19724

**Comment by Malderin** [comment]
> The watchdog problem is fixed here: #19724

the fix did not help, the bootloop was preserved

**Comment by rhapsodyv** [comment]
I tested *your* configs in my Nano V2 + MKS TS 35, using #19724, it boot normally. 100%

**Comment by th0m4sek** [comment]
Problem is still there and it's seems to be related to watchdog. My MKS robin nano 1.2 is not starting every time. With new bug fix problem is still present. I've commented #define USE_WATCHDOG and it's booting.

**Comment by Malderin** [comment]
> Problem is still there and it's seems to be related to watchdog. My MKS robin nano 1.2 is not starting every time. With new bug fix problem is still present. I've commented #define USE_WATCHDOG and it's booting.

I confirm, I still have a problem with active USE_WATCHDOG

**Comment by rhapsodyv** [comment]
@makerbase-mks is possible of some nano boards came with the hardware watchdog enabled? Or some bootloader version turning watchdog on before marlin start?

**Comment by rhapsodyv** [comment]
> > Problem is still there and it's seems to be related to watchdog. My MKS robin nano 1.2 is not starting every time. With new bug fix problem is still present. I've commented #define USE_WATCHDOG and it's booting.
> 
> 
> 
> I confirm, I still have a problem with active USE_WATCHDOG

The problem is with nano v1.2 or nano v2?

**Comment by Malderin** [comment]
> > > Problem is still there and it's seems to be related to watchdog. My MKS robin nano 1.2 is not starting every time. With new bug fix problem is still present. I've commented #define USE_WATCHDOG and it's booting.
> > 
> > 
> > I confirm, I still have a problem with active USE_WATCHDOG
> 
> The problem is with nano v1.2 or nano v2?

I have nano v.2, @th0m4sek have v.1.2.
It looks like problems are encountered on both board versions.

**Comment by rhapsodyv** [comment]
Here, both nano v1.2 and nano v2 with bugfix + watchdog enabled. 

Or we are testing different marlin code base, or MKS have different setups for the same board...

![IMG_0203](https://user-images.githubusercontent.com/81722/95999992-d15f1d00-0e0c-11eb-8d34-571194a90a20.jpg)
![IMG_0204](https://user-images.githubusercontent.com/81722/96000001-d328e080-0e0c-11eb-8746-e3320b43e298.jpg)

**Comment by Malderin** [comment]
> Here, both nano v1.2 and nano v2 with bugfix + watchdog enabled.
> 
> Or we are testing different marlin code base, or MKS have different setups for the same board...
> 
> ![IMG_0203](https://user-images.githubusercontent.com/81722/95999992-d15f1d00-0e0c-11eb-8d34-571194a90a20.jpg)
> ![IMG_0204](https://user-images.githubusercontent.com/81722/96000001-d328e080-0e0c-11eb-8746-e3320b43e298.jpg)

Oк. You can test this firmware for Robin nano v.2? 
This is compiled from the latest bugfix sources and causes a bootloop on my board.

[Robin_nano35.zip](https://github.com/MarlinFirmware/Marlin/files/5378707/Robin_nano35.zip)

**Comment by rhapsodyv** [comment]
> [Robin_nano35.zip](https://github.com/MarlinFirmware/Marlin/files/5378707/Robin_nano35.zip)

Your firmware reboot my board. So, the problem is not the board. Seems your marlin codebase is outdated.

Can you test with a "fresh" copy and build?

Try this firmware that I compiled now, for nano v2:

[Robin_nano35.bin.zip](https://github.com/MarlinFirmware/Marlin/files/5378739/Robin_nano35.bin.zip)

**Comment by Malderin** [comment]
> > [Robin_nano35.zip](https://github.com/MarlinFirmware/Marlin/files/5378707/Robin_nano35.zip)
> 
> Ваша прошивка перезагрузит мою плату. Значит, проблема не в плате. Кажется, ваша кодовая база марлина устарела.
> 
> Можете ли вы протестировать «свежую» копию и собрать?
> 
> Попробуйте эту прошивку, которую я скомпилировал сейчас, для nano v2:
> 
> [Robin_nano35.bin.zip](https://github.com/MarlinFirmware/Marlin/files/5378739/Robin_nano35.bin.zip)

Indeed, the problem seems to be in my copy of marlin. The question is closed, thanks!

**Comment by Malderin** [comment]
@rhapsodyv , I found where I had the problem that was causing the bootloop.
In file Marlin\src\lcd\extui\lib\mks_ui\SPI_TFT.cpp in section:
void TFT::LCD_init() {
  tftio.InitTFT();
  #if PIN_EXISTS(TFT_BACKLIGHT)
    OUT_WRITE(TFT_BACKLIGHT_PIN, LOW);
  #endif
  delay(100);
  LCD_clear(0x0000);
  LCD_Draw_Logo();
  #if PIN_EXISTS(TFT_BACKLIGHT)
    OUT_WRITE(TFT_BACKLIGHT_PIN, HIGH);
  #endif
  #if HAS_LOGO_IN_FLASH
    delay(2000);
  #endif
}
Instead of delay (2000) I had delay (4000) specified. I returned 2000 and the bootlap was gone. It's strange ...

**Comment by th0m4sek** [comment]
I'm suspecting some problems with my microsd card because firmware upload was also not always success. I used different card this time and i will observe printer.
