### ISSUE TITLE
[BUG] MKS UI does not show gcode preview image

### ISSUE THREAD

**Issue by Malderin** [MarlinFirmware/Marlin#19914]
Board MKS robin nano v2
Marlin 2.0.x - last bugfix

### Bug Description

In the generated gcode through the plugin "mks wifi", the model preview on the memory card is not displayed (displayed "no data")
Software - Cura v. 4.7.1, mks wifi plugin v. 1.0.2 (from cura store).

### My Configurations

[Conf.zip](https://github.com/MarlinFirmware/Marlin/files/5440936/Conf.zip)

### Steps to Reproduce

1. Install Cura slicer, install mks wifi plugin from cura store;
2. Slice any model and save on sd card with option "save as tft file";
![1](https://user-images.githubusercontent.com/52313714/97219276-cf1c9b80-17da-11eb-8ea2-92ebf1d6d3fd.jpg)
3. Insert sd card into printer and click "printing"
4. "No data"
![2](https://user-images.githubusercontent.com/52313714/97219186-b1e7cd00-17da-11eb-9573-bded99e09af9.jpg)

#### Additional Information

1. My test gcode file with the preview of the model:
[simple cube.zip](https://github.com/MarlinFirmware/Marlin/files/5440987/simple.cube.zip)
2. The preview is displayed normally during printing
![3](https://user-images.githubusercontent.com/52313714/97219888-b95ba600-17db-11eb-9e4b-c6f0d19f1849.jpg)

**Comment by rhapsodyv** [comment]
Fixed here:  #20564, can you test it?

**Comment by Malderin** [comment]
> Fixed here: #20564, can you test it?
already better, but still there is a reception
![IMG_20201225_142636268](https://user-images.githubusercontent.com/52313714/103137043-9879d900-46d6-11eb-9baa-f1b1b96ae031.jpg)
![IMG_20201225_142647675](https://user-images.githubusercontent.com/52313714/103137046-9adc3300-46d6-11eb-8943-c05f214694b8.jpg)

**Comment by rhapsodyv** [comment]
I was testing with just one file. Now it's ok, I guess. Can you try again? #20564

**Comment by Malderin** [comment]
> I was testing with just one file. Now it's ok, I guess. Can you try again? #20564

everything is fine 
![IMG_20201225_175323993](https://user-images.githubusercontent.com/52313714/103140069-5f039680-46f3-11eb-9d2f-a67bd8d6d2f4.jpg)

**Comment by X-Ryl669** [comment]
Please reopen, the fix in #20564 does not work for me.
It still crash the printer when listing the files if one of them has a preview. I'm generating the preview like it's displayed above (via MKS Cura plugin)

This is the resulting file (unzip to a SD Card and try to list the files):
[SP_MU~1.GCO.zip](https://github.com/MarlinFirmware/Marlin/files/5747297/SP_MU.1.GCO.zip)
I can provide other if you want.

I'm using a MKS Robin Nano 35 (so it's a 480x320 screen and the expected icons are 100x100 not 50x50 as show above).

I've already fixed this in the MKS's [PR31](https://github.com/makerbase-mks/Marlin-2.x.x/pull/31). 
The fix is more complex than the proposed solution since there is both a bug in the file parsing and in the expected icon size.

Currently, the status of the MKS's UI is not clear. I can't really report bug on the PR #20191 since it's not in master, and if I'm reporting bugs to MKS's branch, it's delaying inclusion in Marlin as it has not settled yet.

**Comment by Malderin** [comment]
@X-Ryl669 reopened

**Comment by X-Ryl669** [comment]
With this fix, the printer crashes on the 3rd file (none displayed):
![image](https://user-images.githubusercontent.com/3277165/103216059-5db1b400-4915-11eb-9ff2-82d0651ccac6.png)

With my fix, the printer is happy:
![image](https://user-images.githubusercontent.com/3277165/103217065-fb0de780-4917-11eb-8a0d-80c164a3c879.png)

(Sorry for the poor quality of the picture, I'm using the printer's webcam here)

**Comment by rhapsodyv** [comment]
The file you attached is a invalid gcode. It have dirty on top, like part of a email. Just remove the dirty and it should work:
Dirty:
```
--boundary_.oOo._F2003otnPwbPRz13/F4h0s+GUovex2zD
Content-Disposition: form-data; name="file"; filename="SP_Mutter.gcode"

```

<img width="843" alt="Screen Shot 2020-12-28 at 10 24 40" src="https://user-images.githubusercontent.com/81722/103217259-f38a1680-48f6-11eb-8e04-f11f9964f75f.png">

**Comment by X-Ryl669** [comment]
Sorry to bother you, but I haven't done anything to the file (it's what's produced by MKS WIFI Cura plugin). I have tens of such files on the SD card and they are all like this. There are being written as-is from the MKS's WIFI module firmware. MKS wifi module is using genuine firmware. 

**AND** It doesn't matter since the code is correctly finding the first position of the `simage` part and storing this position in variable `sd_read_base_addr` as expected. It works since the code is searching for `;simage` in `lv_open_gcode_file` and there is one (so anything before this part is completely ignored).

Then,  remove them, and you'll see the file are **still crashing** the printer (because of the wrong size).
Please notice that GCODE files are text file and the end of line characters should not have any influence. Yet, the current code **expect** that lines are separated by '\r' char and not `\r\n` or `\n`. This means that opening a GCode file and saving them in any text editor (or any GCode processor) will mangle the end of lines and break the code expecting a `\r` only, leading to a printer crash.

The bug is still present, removing the lines does not change anything. Please reopen.

**Comment by rhapsodyv** [comment]
This should be enough: https://github.com/MarlinFirmware/Marlin/pull/20589
