### ISSUE TITLE
Full graphic LCD - Not showing X, Y or Z location during print.

### ISSUE THREAD

**Issue by mr-sneezy** [MarlinFirmware/Marlin#2319]
Hi All,
Not sure if this is a 'me' bug or a firmware bug. 
Since updating to 1.0.3 Dev a few weeks back I notice that the display no longer shows where the print head currently is. In particular it was good to see how far up the build plate the Z axis was during the print.
I've checked during a few prints and the X, Y & Z mm display bar on the graphics LCD just stay at ---.-- all print long now...

**Comment by AnHardt** [comment]
The display is showing ---.-- now when the printer does not know its position.
Especially before homing, or when the motors where shut down.
Since #2216  also DISABLE_AXIS is respected in conjunction with DEFAULT_STEPPER_DEACTIVE_TIME instead of shutting down **all** steppers.
Should work now (since 2015/06/10).

**Comment by mr-sneezy** [comment]
Thanks for the reply, and I must admit that I can't understand the issue #2216 after reading all of it, I will trust that you think it's related to what I see above :)

One thing, to make sure I explained it well enough, the graphic LCD doesn't show real mm position even while printing, not just before homing etc. 
For sure it makes sense that it would show ---.-- before homing has been done.
With 1.0.2 Release I had no issue.
Thanks.

**Comment by AnHardt** [comment]
Let me try to expain.
- When the printer is switched on it does not know where it is - displays ---.
- After the printer is homed an axis the printer knows where it is - displays coordinates for that axis.
- When an axis is not active its motor is switched off - depending on DISABLE_AXIS. When a motor is switched off it will skip to the next full step - so its position is unknown again - consequently the display shows --- again.
- When DEFAULT_STEPPER_DEACTIVE_TIME is over (starting with the last move), before #2216 all steppers where switched off, regardless of the DISABLE_AXIS settings. This can happen, for example, during heating up the bed (M190).

The --- was implemented after the release of the `Release`.

**Comment by Nandox7** [comment]
I got recently a Full Graphics display and I've noticed the same.
I understand that the printer needs to perform the homing before it can "locate" itself.

But for example this photo was taken during a printing job and it still doesn't display any coordinates.
https://goo.gl/photos/QPqwy6jtsMMi6raA6

I can't recall but I think even before with 1.0.3 dev I wasn't getting the coordinates even with the UltraLCD.

**Comment by mr-sneezy** [comment]
Yep, that photo is what I get now too during a print, and that's not what it used to be before my firmware update.

AnHart thanks for dumbing it down for me.
I did fully understand that the display would read ---.-- when the steppers were either off or at a unknown location, that is quite obvious, but I'm ONLY talking about during an actual running print job here, not during the heating or before homing...

What I'm confused with now is, is this a real code change for a reason and will stay this way now, or is it a bug and will go back to the way it used to be in 1.0.2 ?

**Comment by AnHardt** [comment]
@Nandox7 
--- was introduced with
https://github.com/MarlinFirmware/Marlin/commit/1a4a09c26f6ed206970668911e816c5539d37954 
on Mai 14, 2015
1.0.2 was released Mar 04, 2015.
`Development` was the default download (branch) until around Mai 20, 2014.

**Comment by AnHardt** [comment]
@mr-sneezy 
So check your settings for DISABLE_AXIS.
The change was intentionally.

**Comment by ntoff** [comment]
> When an axis is not active its motor is switched off - depending on DISABLE_AXIS. When a motor is switched off it will skip to the next full step - so its position is unknown again - consequently the display shows --- again.

stupidest

idea

ever.

**Comment by eboston** [comment]
> stupidest
> 
> idea
> 
> ever.

Which part are you saying is the stupid idea?  If it is about skipping to the next full step when switched off, that is because of physics, not because of design.  It takes current to hold the motor between full steps.

**Comment by mr-sneezy** [comment]
Are you really saying that you turn off the Z axis stepper during printing of print layers (lets just discuss only Z here at the moment), and that the head height position is therefore unknown in Z ?

(Also, are we talking about microstepping here verses full steps, because I was not aware my Melzi board did any microstepping, maybe my ignorance showing).

**Comment by Nandox7** [comment]
The current structure is a bit messy, what should be the branch to checkout in order to test this?
I'm running the code from tag 1.1 at the moment.

**Comment by Nandox7** [comment]
Btw I noticed that it got even more weird halfway during a print it started showing jus the values for the Y axis.

**Comment by Wackerbarth** [comment]
The tag 1.1 is a “beginning of development” tag. — You want to use the “dev" or “Development” branch to get the latest development code. (They are the same except that the dev version has the commits rebased to provide a cleaner history for the next release.)

**Comment by mr-sneezy** [comment]
If it were to come to a vote, I'd prefer to have X,Y & Z position shown during prints and have that as the default behaviour like before.
 I spent much time making sure I set the motor current limiting properly and have the right amount of heatsinking to handle the motor holding on all the time. Fixing hardware issues in software could be called lazy...
My 2 cents, and thanks for efforts with the firmware, on the whole it's a good bit of code.

**Comment by AnHardt** [comment]
@mr-sneezy 
So don't change the default value for:

> #define DISABLE_X false
> #define DISABLE_Y false
> #define DISABLE_Z false

in Configuration.h
and use the ' Development' branch after June 11, 2015,
or set DEFAULT_STEPPER_DEACTIVE_TIME to 0 in Configuration_adv.h

**Comment by Nandox7** [comment]
@Wackerbarth thank you!
I'll merge my local repo with it and give it a try.

**Comment by thinkyhead** [comment]
> Fixing hardware issues in software could be called lazy

We try to assiduously avoid that. The display of "---" for unknown coordinate is meant to inform the user that the printer doesn't know where it is, for whatever reason. It wasn't _precisely_ designed to happen when a motor turns off during a print, but I support it (or something like it) nonetheless, because users may not realize that turning off the motors during printing is a cause of printing problems (which is why `axis_known_position[AXIS]` gets cleared whenever an axis motor is disabled.) Meanwhile, most feedback we get is to get rid of the useless display of X and Y during printing.

**Comment by mr-sneezy** [comment]
Yes agree that X & Y are not useful during print for me either. Z definitely was though, as I could keep an eye out for a particular layer about to start, then watch it for issues. I did this often while dialing in the Prusa i3. Perhaps the ---.-- could show 'MotOff' when the Z motors are disabled (the Prusa i3 has two).
Also can layer height be indicated from the G-code line currently being printed instead ?

**Comment by Nandox7** [comment]
Agreed, I don't care much for the X & Y but I definitely use the Z a lot for different purposes like checking printing progress.

In the mean time I loaded the latest 'Development' code and it seems to be working better, I can see the values showing up after the G28 is done.

**Comment by AnHardt** [comment]
@mr-sneezy 

> Also can layer height be indicated from the G-code line currently being printed instead ?

No. We could calculate where z is supposed to be - not where we are.

**Comment by mr-sneezy** [comment]
If we can't have actual Z position then a calculation from the G-code would be good enough for me.

**Comment by mr-sneezy** [comment]
I've downloaded the current Dev branch tonight and installed it on the Prusa i3.
Yes X, Y and Z are updating values during a print. 
Like spoken about above, X & Y don't have much use, but Z does for me, so I'm happy about that.

About the actual display, I note that the xxx.xx values now show xxx with no decimal when the value is a whole number. i.e. with no trailing .00
Not sure if that was the coders intention....

**Comment by thinkyhead** [comment]
> I note that the xxx.xx values now show xxx with no decimal when the value is a whole number

Yes, the change that was made to improve the readability of the display.

> Downloaded the current Dev branch . Yes X, Y and Z are updating values during a print.

Excellent! Closing the issue.
