### ISSUE TITLE
[BUG] G28 causes an out of bounce move on IDEX system when T1 is active

### ISSUE THREAD

**Issue by rondlh** [MarlinFirmware/Marlin#25296]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Issuing a G28 causes an out of bounce move when issued while T1 is active on an IDEX system. T1 tries to move to the homing position of T0, which is unreachable.

### Bug Timeline

Don't know

### Expected behavior

Move T1 within the predefined limits.

### Actual behavior

T1 tries to move to the T0 homing position, in my case it's stopped because of soft endstops.

### Steps to Reproduce

1. Issue a T1 on an IDEX system
2. Issue an G28 (home printer)
3. After the homing is completed, T1 tries to go to the home position of T0

### Version of Marlin Firmware

Latest (2023-01-23)

### Printer model

Custom

### Electronics

MKS Monster8 V1.0

### Add-ons

BTT TFT35

### Bed Leveling

UBL Bilinear mesh

### Your Slicer

Cura

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

### Additional information & file uploads

The configuration holds the settings for 3 printers, in this case IRON_IDEX is active.
[Configuration_adv.zip](https://github.com/MarlinFirmware/Marlin/files/10517009/Configuration_adv.zip)

**Comment by toreandreas** [comment]
Confirmed. Do not use '#define Z_AFTER_HOMING  10'.
Use '//#define Z_AFTER_HOMING  10'.
Forgot to include: I think it's also a problem in previous versions, but then it wasn't included by default.

**Comment by cbaugher** [comment]
Also confirmed, but a bit different.  On my IDEX, issuing a G28 followed by another manual move will cause the active tool head and the Y axis to move together very slowly for a period of time (20 seconds or so?).  After this time they'll rapid move back to where they were and stop.  At this point manual moves are executed correctly.

Commenting out '#define Z_AFTER_HOMING  10' DOES NOT fix the problem.
EDIT:  After further testing the problem remains.  Initially it appeared to have been fixed, but turns out no.
EDIT2:  It's confusing because the problem doesn't happen on the first G28 after the machine is powered up.  But it does seem to happen on subsequent G28 calls.  Also sometimes the Z axis will do this phantom move too.


Configs attached.
Tested with latest bugfix2.1.x source as of Feb 1st.

C|
[Config.zip](https://github.com/MarlinFirmware/Marlin/files/10665117/Config.zip)

**Comment by nickm324** [comment]
This issue has existed since 2.0.X and still exists. This an AutoPark issue that T1 always tries to move to T0 home. This even occurs when doing a Filament Change, after the nozzle heats up T1 will quickly move left to T0 home and crashes into the T0.
