### ISSUE TITLE
[BUG] Crash during Print, LA, IS, Bugfix.2.1x

### ISSUE THREAD

**Issue by jesterhead82** [MarlinFirmware/Marlin#25553]
### Did you test the latest `bugfix-2.1.x` code?

Yes, and the problem still exists.

### Bug Description

Maybe related to
#25541 
#25474 

Printer crashes during print @2.88mm Layer, tried on 2 different sd cards
Prints fine if I disable LA, ~50/100mm Print speeds, IS @ ~43, LA 0.02, ESTEPS ~700

[Configuration.zip](https://github.com/MarlinFirmware/Marlin/files/11053618/Configuration.zip)
[GCode.zip](https://github.com/MarlinFirmware/Marlin/files/11053629/GCode.zip)

### Steps to Reproduce

[](url)

### Version of Marlin Firmware

Bugfix 2.1.x as of this week

### Printer model

Custom Corexy

### Electronics

BTT 1.4T

### Bed Leveling

ABL Linear grid

### Your Slicer

Prusa Slicer

### Host Software

None

### Don't forget to include

- [X] A ZIP file containing your `Configuration.h` and `Configuration_adv.h`.

**Comment by ThomasToka** [comment]
I can confirm that last commits are somehow faulty. I poke around today around my printer stopping at my usual cube at around 40%.

My last working build has this as last commit: https://github.com/MarlinFirmware/Marlin/commit/10983d0cfe3e353ba465cfcadf8aeb51327f1197

Will disable LA now to check if it works without LA with my recent includes of the latest commits.

EDIT: Confirmed. Disabling LA fixes it. IS stayed enabled. My printer is a E3S1Pro with TMC2208_STANDALONE.

**Comment by ThomasToka** [comment]
Reverting this one fixes it https://github.com/MarlinFirmware/Marlin/commit/ca77850cbb8ed57d4cdcf29a12a278d6bfa5c0d5#

I have not fully understood it but maybe this missing else here is it: 

https://github.com/MarlinFirmware/Marlin/pull/25541/commits/e8b0f38fef0909dd05cecb6655026f9f83765f47

**Comment by thisiskeithb** [comment]
@tombrazier Can you take a look at this?

**Comment by tombrazier** [comment]
@jesterhead82 @ThomasToka Can you describe exactly what your printer does at the point where the print fails? My guess is movement freezes and then after a few seconds the firmware reboots. But if it is something other than that please describe the behaviour. Also: does the E stepper have any noticeable behaviour when the crash occurs?

**Comment by tombrazier** [comment]
> I have not fully understood it but maybe this missing else here is it:

@ThomasToka What mainboard do you have? I think @jesterhead82 has a 32 bit MCU, in which case that code is not compiled.

**Comment by ThomasToka** [comment]
print stops and printer reboots. always at the same position. cube at around 40%.

i have creality f4 board on a ender 3 s1 pro. removing the commit fixes it.

**Comment by ThomasToka** [comment]
nothing else hearable.

**Comment by jesterhead82** [comment]
> > I have not fully understood it but maybe this missing else here is it:
> 
> @ThomasToka What mainboard do you have? I think @jesterhead82 has a 32 bit MCU, in which case that code is not compiled.

Board has a LPC1769, so yes.

As for the stepper, there is some "eechy" noise shortly before the reboot, i guess some motor is doing something stupid. But it could be the board/display maybe, could try again tomorrow is that would be helpfull..

**Comment by tombrazier** [comment]
It could just possibly be a division by zero caused by the changes to all the calls to `calc_timer_interval()` in ca77850. Could one or both of you try changing them back?

**Comment by ThomasToka** [comment]
yes as i said if i revert this commit it works.

**Comment by PendulumPit** [comment]
I setup the latest bugfix the other day to do a speed test on a benchy  and got through that no issue. After I turned on LA as usual and printer would stop and reboot. Tried again and same.  I was going to mention this the other day but I got busy with work.
Was trying to beat Tom's 13 minute benchy lol I failed from a layer shift :)

**Comment by thisiskeithb** [comment]
> As for the stepper, there is some "eechy" noise shortly before the reboot

My Prusa Bear with a BTT002 (STM32F4) has been printing all day with `bugfix-2.1.x` (724ba4b) without issue, but the Biqu Hurakan with Manta M4P (STM32G0) freezes & reboots in the same spot consistently with a similar "eechy" symptom after ~4-5 layers. Both are running Linear Advance & Input Shaping is disabled.

After reverting ca77850, the reboots stop.

**Comment by tombrazier** [comment]
Could someone test #25557?

**Comment by ThomasToka** [comment]
printing. result will follow in 20 min.

**Comment by ThomasToka** [comment]
Confirmed. Works again.

**Comment by ThomasToka** [comment]
Trying now a print with the follow up https://github.com/MarlinFirmware/Marlin/pull/25557/commits/a3c4f25a7a850c6cca40136a4f8201b4353e8939 .

result in some minutes..

**Comment by ThomasToka** [comment]
Nope crashed again on same position.

**Comment by tombrazier** [comment]
Thanks. So it appears that it's not a division by zero. I would really like to understand what is going on before proceeding.

I don't have time now to try and narrow it down but if anyone wants to play, it would be good to know exactly which of the four calls to `calc_timer_interval()` is the one that is causing the error. And if anyone is able to insert a `SERIAL_ECHOLNPGM`to report the offending value that is passed to `calc_timer_interval()` that would be very helpful.

**Comment by ThomasToka** [comment]
Can you give me a matching SERIAL_ECHOLNPGM so i could try?

**Comment by tombrazier** [comment]
For the call to `calc_timer_interval()` on around line 2260 it would be
```
SERIAL_ECHOLNPGM("step_rate ", (acc_step_rate + la_step_rate) >> current_block->la_scaling);
```

That will print out on the serial terminal, assuming you're using something like Octoprint or Prontrface.

**Comment by tombrazier** [comment]
And you can keep adding pairs of strings and values. e.g.
```
SERIAL_ECHOLNPGM("step_rate ", (acc_step_rate + la_step_rate) >> current_block->la_scaling, " asr ", acc_step_rate, " lsr ", la_step_rate, " las ", current_block->la_scaling);
```

**Comment by ThomasToka** [comment]
Can you give me a examples for all 4? I will then do the tests and post. I dont know what you exactly need on the four points.
But can invest the time to debug.

**Comment by tombrazier** [comment]
Just copy the expression that is passed to `calc_timer_interval()` and, if it makes sense, also the variables that make up that expression. Sorry to be difficult, I just really need to be doing something else today.

**Comment by ThomasToka** [comment]
Sorry i am not that good in serial operations.. but will help best i can.

1)

```
SERIAL_ECHOLNPGM("step_rate ", (acc_step_rate + la_step_rate) >> current_block->la_scaling, " asr ", acc_step_rate, " lsr ", la_step_rate, " las ", current_block->la_scaling);

la_interval = calc_timer_interval((acc_step_rate + la_step_rate) >> current_block->la_scaling);
```
            
 2) 
 
```
SERIAL_ECHOLNPGM("step_rate2 ", (reverse_e ? la_step_rate - step_rate : step_rate - la_step_rate) >> current_block->la_scaling, " sr ", step_rate, " lsr ", la_step_rate, " las ", current_block->la_scaling);
 
la_interval = calc_timer_interval((reverse_e ? la_step_rate - step_rate : step_rate - la_step_rate) >> current_block->la_scaling);
 ```

3)

```
SERIAL_ECHOLNPGM("step_rate3 ", (current_block->initial_rate + la_step_rate) >> current_block->la_scaling, " lsr ", la_step_rate, " las ", current_block->la_scaling);

la_interval = calc_timer_interval((current_block->initial_rate + la_step_rate) >> current_block->la_scaling);
```
 
 like this or after the la_interval ?

**Comment by ThomasToka** [comment]
```
Recv: step_rate 5396 asr 1396 lsr 4000 las 0
Recv: step_rate 5601 asr 1601 lsr 4000 las 0
Recv: step_rate 5755 asr 1755 lsr 4000 las 0
Recv: step_rate 5866 asr 1866 lsr 4000 las 0
Recv: step_rate 5938 asr 1938 lsr 4000 las 0
Recv: step_rate 5979 asr 1979 lsr 4000 las 0
Recv: step_rate 5997 asr 1997 lsr 4000 las 0
Recv: step_rate3 6000 lsr 4000 las 0
Recv: step_rate3 6000 lsr 4000 las 0
Recv: step_rate3 6000 lsr 4000 las 0
Recv: step_rate3 6000 lsr 4000 las 0
Recv: step_rate3 6000 lsr 4000 las 0
Recv: step_rate3 6000 lsr 4000 las 0
Recv: step_rate3 6000 lsr 4000 las 0
```

it spams so lets see what comes out at 40% ;)

**Comment by ThomasToka** [comment]
Oh it emediately stopped at the skirt.

Print stopped, but terminal keeps spamming messages.

**Comment by tombrazier** [comment]
Is it the same message? What does it say? And which calc_timer_interval does it apply to?

**Comment by ThomasToka** [comment]
sorry had to restart my octoprint as the logs were not written automatically.

just started a print again.

It looks like it stopps extruding.

Will post log in some minutes.

I could not see anything relevant while live watching last time.

**Comment by ThomasToka** [comment]
[serial(1).log](https://github.com/MarlinFirmware/Marlin/files/11062452/serial.1.log)
[octoprint(3).log](https://github.com/MarlinFirmware/Marlin/files/11062453/octoprint.3.log)

cant see anything. will stop debugging now as i dont have any time left today.

**Comment by ThomasToka** [comment]
short video

**Comment by thisiskeithb** [comment]
Adding some debug lines causes the print to fail a lot faster now. I can do a basic purge line and then the machine reboots right after it moves to the middle of the bed to start printing the actual part. It fails right after this call:

https://github.com/MarlinFirmware/Marlin/blob/28666f2fb28e8b68f641e507359a72dbf4bc117a/Marlin/src/module/stepper.cpp#L2387

Log output:

```log
Send: N51 G1 X148.024 Y133.735 E.12833*102
Recv: Call 3 Start
Recv: Call 3 End
Recv: 
Communication timeout while printing, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
[...]
Unexpected error while reading serial port, please consult octoprint.log for details: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:3997
```

**Comment by tombrazier** [comment]
What value for la_interval is returned, Keith? And what was passed to calc_timer_interval()?

**Comment by thisiskeithb** [comment]
> What value for la_interval is returned, Keith? And what was passed to calc_timer_interval()?

I'll recompile and check. Many of those variables were "not declared in this scope" when adding your debug output & would not compile (that's why I wrapped the calls the way I did), but here's a copy of `stepper.cpp` that compiles for me:

[stepper.cpp.zip](https://github.com/MarlinFirmware/Marlin/files/11064415/stepper.cpp.zip)

<details><summary>And the diff for faster reading with offending debug lines/variables commented out:</summary>
<p>

```diff
diff --git a/Marlin/src/module/stepper.cpp b/Marlin/src/module/stepper.cpp
index 5c0034a..57ea3e4 100644
--- a/Marlin/src/module/stepper.cpp
+++ b/Marlin/src/module/stepper.cpp
@@ -2254,7 +2254,16 @@ hal_timer_t Stepper::block_phase_isr() {
         #if ENABLED(LIN_ADVANCE)
           if (la_active) {
             const uint32_t la_step_rate = la_advance_steps < current_block->max_adv_steps ? current_block->la_advance_rate : 0;
+            SERIAL_EOL();
+            SERIAL_ECHO("Call 1 Start");
+            SERIAL_EOL();
             la_interval = calc_timer_interval((acc_step_rate + la_step_rate) >> current_block->la_scaling);
+            SERIAL_ECHOLNPGM("step_rate: ", (acc_step_rate + la_step_rate) >> current_block->la_scaling);
+            SERIAL_ECHOLNPGM("asr: ", acc_step_rate);
+            SERIAL_ECHOLNPGM("lsr: ", la_step_rate);
+            SERIAL_ECHOLNPGM("las: ", current_block->la_scaling);
+            SERIAL_ECHO("Call 1 End");
+            SERIAL_EOL();
           }
         #endif
 
@@ -2326,7 +2335,16 @@ hal_timer_t Stepper::block_phase_isr() {
             const uint32_t la_step_rate = la_advance_steps > current_block->final_adv_steps ? current_block->la_advance_rate : 0;
             if (la_step_rate != step_rate) {
               bool reverse_e = la_step_rate > step_rate;
+              SERIAL_EOL();
+              SERIAL_ECHO("Call 2 Start");
+              SERIAL_EOL();
               la_interval = calc_timer_interval((reverse_e ? la_step_rate - step_rate : step_rate - la_step_rate) >> current_block->la_scaling);
+              //SERIAL_ECHOLNPGM("step_rate: ", (acc_step_rate + la_step_rate) >> current_block->la_scaling);
+              //SERIAL_ECHOLNPGM("asr: ", acc_step_rate);
+              SERIAL_ECHOLNPGM("lsr: ", la_step_rate);
+              SERIAL_ECHOLNPGM("las: ", current_block->la_scaling);
+              SERIAL_ECHO("Call  2 End");
+              SERIAL_EOL();
 
               if (reverse_e != motor_direction(E_AXIS)) {
                 TBI(last_direction_bits, E_AXIS);
@@ -2384,7 +2402,16 @@ hal_timer_t Stepper::block_phase_isr() {
 
           #if ENABLED(LIN_ADVANCE)
             if (la_active)
+              SERIAL_EOL();
+              SERIAL_ECHO("Call 3 Start");
+              SERIAL_EOL();
               la_interval = calc_timer_interval(current_block->nominal_rate >> current_block->la_scaling);
+              //SERIAL_ECHOLNPGM("step_rate: ", (acc_step_rate + la_step_rate) >> current_block->la_scaling);
+              //SERIAL_ECHOLNPGM("asr: ", acc_step_rate);
+              //SERIAL_ECHOLNPGM("lsr: ", la_step_rate);
+              SERIAL_ECHOLNPGM("las: ", current_block->la_scaling);
+              SERIAL_ECHO("Call 3 End");
+              SERIAL_EOL();
           #endif
         }
 
@@ -2706,7 +2733,16 @@ hal_timer_t Stepper::block_phase_isr() {
       #if ENABLED(LIN_ADVANCE)
         if (la_active) {
           const uint32_t la_step_rate = la_advance_steps < current_block->max_adv_steps ? current_block->la_advance_rate : 0;
+          SERIAL_EOL();
+          SERIAL_ECHO("Call 4 Start");
+          SERIAL_EOL();
           la_interval = calc_timer_interval((current_block->initial_rate + la_step_rate) >> current_block->la_scaling);
+          //SERIAL_ECHOLNPGM("step_rate: ", (acc_step_rate + la_step_rate) >> current_block->la_scaling);
+          //SERIAL_ECHOLNPGM("asr: ", acc_step_rate);
+          SERIAL_ECHOLNPGM("lsr: ", la_step_rate);
+          SERIAL_ECHOLNPGM("las: ", current_block->la_scaling);
+          SERIAL_ECHO("Call 4 End");
+          SERIAL_EOL();
         }
       #endif
     }
```

</p>
</details>

I'm using the [default Biqu Hurakan config](https://github.com/MarlinFirmware/Configurations/tree/bugfix-2.1.x/config/examples/BIQU/Hurakan) so you can see which features are enabled.

**Comment by thisiskeithb** [comment]
Updated `stepper.cpp`: [stepper.cpp.zip](https://github.com/MarlinFirmware/Marlin/files/11064587/stepper.cpp.zip)

<details><summary>And the updated diff:</summary>
<p>

```diff
diff --git a/Marlin/src/module/stepper.cpp b/Marlin/src/module/stepper.cpp
index 5c0034a..70f2f64 100644
--- a/Marlin/src/module/stepper.cpp
+++ b/Marlin/src/module/stepper.cpp
@@ -2254,7 +2254,17 @@ hal_timer_t Stepper::block_phase_isr() {
         #if ENABLED(LIN_ADVANCE)
           if (la_active) {
             const uint32_t la_step_rate = la_advance_steps < current_block->max_adv_steps ? current_block->la_advance_rate : 0;
+            SERIAL_EOL();
+            SERIAL_ECHO("Call 1 Start");
+            SERIAL_EOL();
             la_interval = calc_timer_interval((acc_step_rate + la_step_rate) >> current_block->la_scaling);
+            SERIAL_ECHOLNPGM("la_interval: ", la_interval);
+            SERIAL_ECHOLNPGM("step_rate: ", (acc_step_rate + la_step_rate) >> current_block->la_scaling);
+            SERIAL_ECHOLNPGM("asr: ", acc_step_rate);
+            SERIAL_ECHOLNPGM("lsr: ", la_step_rate);
+            SERIAL_ECHOLNPGM("las: ", current_block->la_scaling);
+            SERIAL_ECHO("Call 1 End");
+            SERIAL_EOL();
           }
         #endif
 
@@ -2326,7 +2336,17 @@ hal_timer_t Stepper::block_phase_isr() {
             const uint32_t la_step_rate = la_advance_steps > current_block->final_adv_steps ? current_block->la_advance_rate : 0;
             if (la_step_rate != step_rate) {
               bool reverse_e = la_step_rate > step_rate;
+              SERIAL_EOL();
+              SERIAL_ECHO("Call 2 Start");
+              SERIAL_EOL();
               la_interval = calc_timer_interval((reverse_e ? la_step_rate - step_rate : step_rate - la_step_rate) >> current_block->la_scaling);
+              SERIAL_ECHOLNPGM("la_interval: ", la_interval);
+              //SERIAL_ECHOLNPGM("step_rate: ", (acc_step_rate + la_step_rate) >> current_block->la_scaling);
+              //SERIAL_ECHOLNPGM("asr: ", acc_step_rate);
+              SERIAL_ECHOLNPGM("lsr: ", la_step_rate);
+              SERIAL_ECHOLNPGM("las: ", current_block->la_scaling);
+              SERIAL_ECHO("Call  2 End");
+              SERIAL_EOL();
 
               if (reverse_e != motor_direction(E_AXIS)) {
                 TBI(last_direction_bits, E_AXIS);
@@ -2384,7 +2404,17 @@ hal_timer_t Stepper::block_phase_isr() {
 
           #if ENABLED(LIN_ADVANCE)
             if (la_active)
+              SERIAL_EOL();
+              SERIAL_ECHO("Call 3 Start");
+              SERIAL_EOL();
               la_interval = calc_timer_interval(current_block->nominal_rate >> current_block->la_scaling);
+              SERIAL_ECHOLNPGM("la_interval: ", la_interval);
+              //SERIAL_ECHOLNPGM("step_rate: ", (acc_step_rate + la_step_rate) >> current_block->la_scaling);
+              //SERIAL_ECHOLNPGM("asr: ", acc_step_rate);
+              //SERIAL_ECHOLNPGM("lsr: ", la_step_rate);
+              SERIAL_ECHOLNPGM("las: ", current_block->la_scaling);
+              SERIAL_ECHO("Call 3 End");
+              SERIAL_EOL();
           #endif
         }
 
@@ -2706,7 +2736,17 @@ hal_timer_t Stepper::block_phase_isr() {
       #if ENABLED(LIN_ADVANCE)
         if (la_active) {
           const uint32_t la_step_rate = la_advance_steps < current_block->max_adv_steps ? current_block->la_advance_rate : 0;
+          SERIAL_EOL();
+          SERIAL_ECHO("Call 4 Start");
+          SERIAL_EOL();
           la_interval = calc_timer_interval((current_block->initial_rate + la_step_rate) >> current_block->la_scaling);
+          SERIAL_ECHOLNPGM("la_interval: ", la_interval);
+          //SERIAL_ECHOLNPGM("step_rate: ", (acc_step_rate + la_step_rate) >> current_block->la_scaling);
+          //SERIAL_ECHOLNPGM("asr: ", acc_step_rate);
+          SERIAL_ECHOLNPGM("lsr: ", la_step_rate);
+          SERIAL_ECHOLNPGM("las: ", current_block->la_scaling);
+          SERIAL_ECHO("Call 4 End");
+          SERIAL_EOL();
         }
       #endif
     }
```

</p>
</details>

`la_interval` was `571` when it failed. Here's some of the log I have before it rebooted (right after the purge line / after the move to the center of the bed):

<details><summary>log output:</summary>
<p>

```prolog
Recv: Call 3 Start
Recv: la_interval: 209
Recv: las: 0
Recv: Call 3 End
Recv: ok
Send: N50 G1 X150.372 Y131.346 E.09582*97
Recv: ok
Send: N51 G1 X148.024 Y133.735 E.12833*102
Recv: Call 3 Start
Recv: la_interval: 571
Recv: las: 0
Recv: Call 3 End
[...]
Recv: 
Communication timeout while printing, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
[...]
Unexpected error while reading serial port, please consult octoprint.log for details: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:3997
```

</p>
</details>

**Comment by tombrazier** [comment]
Keith I should have spotted your "Call 3" code is outside the preceding `if` statement. Needs braces.

**Comment by thisiskeithb** [comment]
> Keith I should have spotted your "Call 3" code is outside the preceding `if` statement. Needs braces.

Those are missing from the current code: 

https://github.com/MarlinFirmware/Marlin/blob/8d3142911c017b542f1b55e9d2c09b68beacadd9/Marlin/src/module/stepper.cpp#L2385-L2388

Here's the updated `stepper.cpp` I used for testing: [stepper.cpp.zip](https://github.com/MarlinFirmware/Marlin/files/11069852/stepper.cpp.zip)

<details><summary>...and the updated diff:</summary>
<p>

```diff
diff --git a/Marlin/src/module/stepper.cpp b/Marlin/src/module/stepper.cpp
index 5c0034a..c7f1171 100644
--- a/Marlin/src/module/stepper.cpp
+++ b/Marlin/src/module/stepper.cpp
@@ -2254,7 +2254,17 @@ hal_timer_t Stepper::block_phase_isr() {
         #if ENABLED(LIN_ADVANCE)
           if (la_active) {
             const uint32_t la_step_rate = la_advance_steps < current_block->max_adv_steps ? current_block->la_advance_rate : 0;
+            SERIAL_EOL();
+            SERIAL_ECHO("Call 1 Start");
+            SERIAL_EOL();
             la_interval = calc_timer_interval((acc_step_rate + la_step_rate) >> current_block->la_scaling);
+            SERIAL_ECHOLNPGM("la_interval: ", la_interval);
+            SERIAL_ECHOLNPGM("step_rate: ", (acc_step_rate + la_step_rate) >> current_block->la_scaling);
+            SERIAL_ECHOLNPGM("asr: ", acc_step_rate);
+            SERIAL_ECHOLNPGM("lsr: ", la_step_rate);
+            SERIAL_ECHOLNPGM("las: ", current_block->la_scaling);
+            SERIAL_ECHO("Call 1 End");
+            SERIAL_EOL();
           }
         #endif
 
@@ -2326,7 +2336,17 @@ hal_timer_t Stepper::block_phase_isr() {
             const uint32_t la_step_rate = la_advance_steps > current_block->final_adv_steps ? current_block->la_advance_rate : 0;
             if (la_step_rate != step_rate) {
               bool reverse_e = la_step_rate > step_rate;
+              SERIAL_EOL();
+              SERIAL_ECHO("Call 2 Start");
+              SERIAL_EOL();
               la_interval = calc_timer_interval((reverse_e ? la_step_rate - step_rate : step_rate - la_step_rate) >> current_block->la_scaling);
+              SERIAL_ECHOLNPGM("la_interval: ", la_interval);
+              //SERIAL_ECHOLNPGM("step_rate: ", (acc_step_rate + la_step_rate) >> current_block->la_scaling);
+              //SERIAL_ECHOLNPGM("asr: ", acc_step_rate);
+              SERIAL_ECHOLNPGM("lsr: ", la_step_rate);
+              SERIAL_ECHOLNPGM("las: ", current_block->la_scaling);
+              SERIAL_ECHO("Call  2 End");
+              SERIAL_EOL();
 
               if (reverse_e != motor_direction(E_AXIS)) {
                 TBI(last_direction_bits, E_AXIS);
@@ -2383,8 +2403,19 @@ hal_timer_t Stepper::block_phase_isr() {
           ticks_nominal = calc_multistep_timer_interval(current_block->nominal_rate << oversampling_factor);
 
           #if ENABLED(LIN_ADVANCE)
-            if (la_active)
+            if (la_active) {
+              SERIAL_EOL();
+              SERIAL_ECHO("Call 3 Start");
+              SERIAL_EOL();
               la_interval = calc_timer_interval(current_block->nominal_rate >> current_block->la_scaling);
+              SERIAL_ECHOLNPGM("la_interval: ", la_interval);
+              //SERIAL_ECHOLNPGM("step_rate: ", (acc_step_rate + la_step_rate) >> current_block->la_scaling);
+              //SERIAL_ECHOLNPGM("asr: ", acc_step_rate);
+              //SERIAL_ECHOLNPGM("lsr: ", la_step_rate);
+              SERIAL_ECHOLNPGM("las: ", current_block->la_scaling);
+              SERIAL_ECHO("Call 3 End");
+              SERIAL_EOL();
+            }
           #endif
         }
 
@@ -2706,7 +2737,17 @@ hal_timer_t Stepper::block_phase_isr() {
       #if ENABLED(LIN_ADVANCE)
         if (la_active) {
           const uint32_t la_step_rate = la_advance_steps < current_block->max_adv_steps ? current_block->la_advance_rate : 0;
+          SERIAL_EOL();
+          SERIAL_ECHO("Call 4 Start");
+          SERIAL_EOL();
           la_interval = calc_timer_interval((current_block->initial_rate + la_step_rate) >> current_block->la_scaling);
+          SERIAL_ECHOLNPGM("la_interval: ", la_interval);
+          //SERIAL_ECHOLNPGM("step_rate: ", (acc_step_rate + la_step_rate) >> current_block->la_scaling);
+          //SERIAL_ECHOLNPGM("asr: ", acc_step_rate);
+          SERIAL_ECHOLNPGM("lsr: ", la_step_rate);
+          SERIAL_ECHOLNPGM("las: ", current_block->la_scaling);
+          SERIAL_ECHO("Call 4 End");
+          SERIAL_EOL();
         }
       #endif
     }

```

</p>
</details>

It still fails right after the move to the center of the bed, after the purge line (where the `.gcode` sets a LA/`M900` value). I also no longer get any "Case #" / debug lines on serial after adding those braces to the "Call 3" section:

<details><summary>Error details:</summary>
<p>

```prolog
Send: N47 G1 X143.803 Y84.524 E.21104*85
[...]
Recv: ok
Send: N48 G1 X145.326 Y96.785 E.47335*90
Recv: ok
Send: N49 G1 X150.372 Y128.845 E1.2434*111
Recv: ok
Send: N50 G1 X150.372 Y131.346 E.09582*97
Recv: ok
Send: N51 G1 X148.024 Y133.735 E.12833*102
Recv: 
Communication timeout while printing, trying to trigger response from printer. Configure long running commands or increase communication timeout if that happens regularly on specific commands or long moves.
[...]
Unexpected error while reading serial port, please consult octoprint.log for details: SerialException: 'device reports readiness to read but returned no data (device disconnected or multiple access on port?)' @ comm.py:_readline:3997
```

</p>
</details>

**Comment by tombrazier** [comment]
> Those are missing from the current code:

It's a C++ thing.

I have replicated a hang on a BTT SKR Mini E3 V3.0. Even with commit ca77850cbb8ed57d4cdcf29a12a278d6bfa5c0d5 reverted, I still get a hang with the debug code in place. I suspect something more subtle is going on.

**Comment by thinkyhead** [comment]
> I have replicated a hang on a BTT SKR Mini E3 V3.0. Even with commit ca77850cbb reverted, I still get a hang with the debug code in place. I suspect something more subtle is going on.

Printing to serial from within an ISR (e.g., `block_phase_isr`) will cause all kinds of mayhem. You can instead set some values in a global array and then print to serial from the main loop.

**Comment by thinkyhead** [comment]
I'm peeking at the code changes since 194f58740a and will just write down my suggestions of things to check, starting with…

- Make sure that `calc_timer_interval` and `calc_multistep_timer_interval` are never returning 0. Logic was updated so that a `ticks_nominal` value of 0 means it needs recalculation. So it should never get set to 0 by anything other than the "please recalculate" code.

- Note that the old "`MULTISTEPPING_LIMIT`" (before there was a "`MULTISTEPPING_LIMIT`")  was 128. So it may be worth setting it to 128 to see if that makes any difference.

- I'm assuming that PR #25541 is the main culprit in the crashing behavior (due to divide-by-zero), but it can't hurt to see if setting `OLD_ADAPTIVE_MULTISTEPPING` makes a difference. The reckoning of time spent within/outside the ISR can depend on various factors, perhaps being chaotically affected by the pauses that may occur with extruder retraction moves.

**Comment by tombrazier** [comment]
Okay so...
- The bug in the OP will always be characterised by the "eechy" sound from the E stepper. (This is the E stepper running as fast as the stepper ISR can generate steps.)
- I have replicated the bug with Keith's gcode. It is, indeed, caused by a division by zero and #25557 solves it. Thinky has merged that PR so I think this issue is resolved.
- Quite a few of the hangs observed above are actually caused by the serial output code I asked people to add. So that just confused things.
- @ThomasToka I am not convinced that you have the same bug because a) lack of "eechy" sound and b) commit ca77850 from #25557 does not resolve it. I also don't think that when you tested either commit of #25557 you had any serial debug statements. So this may be another bug entirely. Can you post your config and gcode?

**Comment by thisiskeithb** [comment]
I'm running the same test print I've been using without all that serial debug stuff on the Biqu Hurakan (BTT Manta M4P / STM32G0) on the latest `bugfix-2.1` (241c062), ~~so I'll report back in a few~~ and the reboot issue has been resolved!.

@tombrazier: Did you see this comment from @RV-from-be: https://github.com/MarlinFirmware/Marlin/pull/25557#issuecomment-1484131460? That PR didn't fully fix the issue apparently.

**Comment by tombrazier** [comment]
Further observation: the small step rate being passed to `calc_timer_interval()` which becomes zero due to the bit shift occurs during deceleration when the E stepper switches from forwards to backwards movement. It is momentary. Even if the number is not zero, there is still a bug because it causes a long delay between updates of `nextAdvanceISR` in `Stepper:isr()` during which time the step rate will have increased significantly but the stepper ISR will have generated only 1 E step. I am considering changing
```
      else if (nextAdvanceISR == LA_ADV_NEVER)          // Start LA steps if necessary
        nextAdvanceISR = la_interval;
```
to
```
      else if (nextAdvanceISR > la_interval)          // Start or accelerate LA steps if necessary
        nextAdvanceISR = la_interval;
```

@thinkyhead

**Comment by tombrazier** [comment]
> Did you see this comment from @RV-from-be: https://github.com/MarlinFirmware/Marlin/pull/25557#issuecomment-1484131460? That PR didn't fully fix the issue apparently.

Thanks for pointing me at that Keith.

**Comment by tombrazier** [comment]
@RV-from-be @ThomasToka Can you test an idea for me please. Change `Stepper::calc_timer_interval()` in `Marlin/src/module/stepper.cpp` from
```
return step_rate ? uint32_t(STEPPER_TIMER_RATE) / step_rate : HAL_TIMER_TYPE_MAX;
```
to
```
return (step_rate > uint32_t(STEPPER_TIMER_RATE) / 65535) ? uint32_t(STEPPER_TIMER_RATE) / step_rate : HAL_TIMER_TYPE_MAX;
```

**Comment by ThomasToka** [comment]
@tombrazier just saw this.. printing.. result in some minutes.

**Comment by thinkyhead** [comment]
I believe this one may be solved, but we should test a variety of conditions just to be sure.

**Comment by thisiskeithb** [comment]
For anyone following this issue / experienced crashes, please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

Be sure to attach a ZIP file containing your `Configuration.h`, `Configuration_adv.h`, and G-code in your reply.

**Comment by vovodroid** [comment]
> please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.

Any specific print options and print duration? I have BTT SKR 2 board.

**Comment by thisiskeithb** [comment]
> Any specific print options and print duration? I gave BTT SKR 2 board.

Were you experiencing board halts with `LIN_ADVANCE` & a K-factor (`M900`) other than 0?

I couldn’t get STM32F4-based boards to halt (including the BTT002 & SKR V2) in my testing of this issue.

**Comment by vovodroid** [comment]
> Were you experiencing board halts with `LIN_ADVANCE` & a K-factor (`M900`) other than 0?

I didn't build Marlin with suspected commits. But I'll try latest build with fixes anyway.

**Comment by vovodroid** [comment]
More than 1 hour print on BTT SKR 2 seems to be OK.

**Comment by dwzg** [comment]
Haven't had a crash again with the most recent bugfix branch. Even a print that would always trigger the crash at a specific point is now running fine on my SKR E3 Turbo.

**Comment by PendulumPit** [comment]
> For anyone following this issue / experienced crashes, please download [`bugfix-2.1.x`](https://github.com/MarlinFirmware/Marlin/archive/bugfix-2.1.x.zip) to test with the latest code and let us know if you're still having this issue.
> 
> Be sure to attach a ZIP file containing your `Configuration.h`, `Configuration_adv.h`, and G-code in your reply.

I will give it a go. I had the issue when testing awhile back. Thanks to the Team for your hard work. :+1:

**Comment by SpannMagoo** [comment]
Crashed right when its about to do purge line. Creality 4.2.7 Ender 3
[Configuration_4.2.7.zip](https://github.com/MarlinFirmware/Marlin/files/11131050/Configuration_4.2.7.zip)
[ringing_tower_56m_0.20mm_200C_PLA-2.0.zip](https://github.com/MarlinFirmware/Marlin/files/11131144/ringing_tower_56m_0.20mm_200C_PLA-2.0.zip)

**Comment by thisiskeithb** [comment]
> Crashed right when its about to do purge line. Creality 4.2.7 Ender 3 [Configuration_4.2.7.zip](https://github.com/MarlinFirmware/Marlin/files/11131050/Configuration_4.2.7.zip)

Can you attach the g-code you were printing with? Which PIO environment did you use?

**Comment by SpannMagoo** [comment]
Posted in same post. Used vscode, Auto Build Marlin.

**Comment by tombrazier** [comment]
@SpannMagoo Can you check whether it still happens in my new test branch?

https://github.com/tombrazier/Marlin/tree/lafreeze2

**Comment by SpannMagoo** [comment]
OK, ran the newest branch as requested. I ran 3 tests and failed on the 2nd test at the purge line. See below for configs and the .gcode
[Configuration_LatestPR4.2.7.zip](https://github.com/MarlinFirmware/Marlin/files/11133322/Configuration_LatestPR4.2.7.zip)
[ringing_tower_56m_0.20mm_200C_PLA-3.0.zip](https://github.com/MarlinFirmware/Marlin/files/11133323/ringing_tower_56m_0.20mm_200C_PLA-3.0.zip)

**Comment by SpannMagoo** [comment]
Also just noticed it only does the first 3 points when doing the g29 and stops.

**Comment by tombrazier** [comment]
Additional info: @SpannMagoo tells me that when the hang occurs, it is an M112 halt, complete with a screen saying "M112 Shutdown". This is not the same bug.

[Edit: looking at the code, it appears that the only way you can get there is if M112 is sent to the printer.]

**Comment by SpannMagoo** [comment]
> Additional info: @SpannMagoo tells me that when the hang occurs, it is an M112 halt, complete with a screen saying "M112 Shutdown". This is not the same bug.
> 
> 
> 
> [Edit: looking at the code, it appears that the only way you can get there is if M112 is sent to the printer.]

This is interesting because I did not have the pi plugged in the last time.

**Comment by tombrazier** [comment]
@SpannMagoo reports (offline conversation) that the M112 bug began after the 18 March edition of bugfix. There were a lot of merges on 18 March and depending on quite where the snapshot occurred which SpannMagoo downloaded, this may or may not mean that there are a lot of other potential changes that could be related to this bug.

I think this probably warrants a new bug report.

As for this one, i.e. #25553, no one else is reporting anything here.

**Comment by thisiskeithb** [comment]
> I think this probably warrants a new bug report.

@SpannMagoo: Please open a new [bug report](https://github.com/MarlinFirmware/Marlin/issues/new/choose) for your issue.

**Comment by ThomasToka** [comment]
I had not the time and capacity to test very much.

But: I did a fresh compile of bugfix-2.1.x downloaded 2 days ago. Enabled LA as always and was not suffering from this problem.

Where i am affected is if a activate this commit with my fork of a ender 3 s1 port: https://github.com/MarlinFirmware/Marlin/commit/ca77850cbb8ed57d4cdcf29a12a278d6bfa5c0d5

Also the follow up fixes for this do not work. If i revert this commit all is good.

I had maybe 25 testers in the last 4 weeks for my firmware fork. All of them Ender 3 s1 Pro or Plus. Only 2 of them suffered also from this commit. Reverting this commit fixed the halts for both affected.

But it may be really something other that this here mentioned. I had on my printer no etchy sound or something. It just halted.

**Comment by cybercatnet** [comment]
I am using the latest build and on the fourth layer it starts printing slow until the print stops completely and the extruder motor starts making noises. The program stops working and does not respond.

**Comment by tombrazier** [comment]
@cybercatnet Could you elaborate a bit please? What do you mean by "the latest build"? And could you post your gcode? And is this repeatable?

**Comment by cybercatnet** [comment]
> @cybercatnet Could you elaborate a bit please? What do you mean by "the latest build"? And could you post your gcode? And is this repeatable?

@tombrazier 

The build [commit 7369a6a](https://github.com/MarlinFirmware/Marlin/commit/7369a6a37b39d89ce92bcfebec74d60ecd74ff22)

Example G-Code [cap_large.zip](https://github.com/MarlinFirmware/Marlin/files/11215819/cap_large.zip)

**Comment by tombrazier** [comment]
Next question: can I have your config please. And what printer / mainboard do you have?

And can you check whether the freeze still happens with my branch [here](https://github.com/tombrazier/Marlin/tree/lafreeze2).

**Comment by tombrazier** [comment]
@ThomasToka What actually is the difference between your fork and upstream Marlin? Looking at your branch [MARLIN-E3S1PRO-FORK-BYTT](https://github.com/ThomasToka/Marlin/tree/MARLIN-E3S1PRO-FORK-BYTT) it appears to be identical.

And could you post your config and platformio.ini please (I realise you might already have done so above but I want the latest and don't have the capacity to search the conversation history).

And do you know whether the reported bugs are on F1, F4 or both?

**Comment by ThomasToka** [comment]
@tombrazier i have rebuild my sources last week on the actual sources and ported the creality code. i will release the commits in the next 30 days cause i have to clean up a bit before public release. with this newer sources the error did not occure once.

it did only occur with two users. both ender3s1pro or plus with creality mainboards. the build it occured was the build before this i used. this was based on the synman release of the creality port. https://github.com/synman/Marlin/tree/bugfix-2.1.x i is reproducable if you add the mentioned commit to this. https://github.com/MarlinFirmware/Marlin/commit/ca77850cbb8ed57d4cdcf29a12a278d6bfa5c0d5

**Comment by ThomasToka** [comment]
Configs: 
[configuartions.zip](https://github.com/MarlinFirmware/Marlin/files/11221238/configuartions.zip)
Platformio: 
[platformio.zip](https://github.com/MarlinFirmware/Marlin/files/11221246/platformio.zip)

**Comment by cybercatnet** [comment]
> Next question: can I have your config please. And what printer / mainboard do you have?
> 
> And can you check whether the freeze still happens with my branch [here](https://github.com/tombrazier/Marlin/tree/lafreeze2).

@tombrazier, sorry for the delay, I tried the version that is in your lafreeze2 branch, the crash problem remains the same, it fails at the same moment, but also specifically the motors brake at different times during printing (this did not happen in the Master branch). I hope it helps, anything let me know.

Printer P3Steel, Arduino Mega2560
[Config lafreeze2.zip](https://github.com/MarlinFirmware/Marlin/files/11278310/Config.lafreeze2.zip)
[Config commit 7369a6a.zip](https://github.com/MarlinFirmware/Marlin/files/11278313/Config.commit.7369a6a.zip)

**Comment by thinkyhead** [comment]
@cybercatnet — Are you still seeing such issues with the current `bugfix-2.1.x`? Is there some earlier point in time between the release of 2.1.2 and today where the problem does not exist?

**Comment by cybercatnet** [comment]
> @cybercatnet — Are you still seeing such issues with the current `bugfix-2.1.x`? Is there some earlier point in time between the release of 2.1.2 and today where the problem does not exist?

@thinkyhead 
Testing the build [commit 3136435](https://github.com/MarlinFirmware/Marlin/commit/3136435c19d2e06253f01010c2d5ca740a78a79e)
Is not crashing but the motors stop some miliseconds, like 250ms, in random moments (short travel times?).
I dont know how to see the commit number in the files for the build where the problem does not exist, the download date was march 7 21:23.
[Config commit 3136435.zip](https://github.com/MarlinFirmware/Marlin/files/11492968/Config.commit.3136435.zip)
