### ISSUE TITLE
No SD-Card support for Red RepRapDiscount Full Graphic Smart Controller under 1.1 RC?

### ISSUE THREAD

**Issue by GrevanGER** [MarlinFirmware/Marlin#2628]
Greetings. 

I've just updated to 1.1 RC thanks to a few helpfull users here. 
But it seems like I am bumping from one problem into the next. 

Right now I am trying to get my Smart Controller going. 
So in the config.h it says:
The RepRapDiscount FULL GRAPHIC Smart Controller (quadratic white PCB)
Sadly this is the only entry for the RepRapDiscount.

And I guess by "white PCB" this line refers to this series of controllers:
http://reprap.org/mediawiki/images/thumb/9/93/RRD_FULL_GRAPHIC_SMART_CONTROLER_INFO.JPG/190px-RRD_FULL_GRAPHIC_SMART_CONTROLER_INFO.JPG

Now my problem is, that I got one of the red ones:
http://forums.reprap.org/addon.php?1,module=embed_images,file_id=38553

The controlls are running fine so far, yet the SD Slot seems not to be supported by this 'driver'.

Has anyone got an idea on how to solve this?

**Comment by epatel** [comment]
Did you activate SDSUPPORT? Somewhere it seem to have changed so one need to do that explicit

**Comment by GrevanGER** [comment]
Yeah. Found it within the massive wall of text right after the Charset settings. 
Uncommenting that line did the trick. Thanks.

**Comment by Reisyukaku** [comment]
I'm having the exact same problem and none of the SD related defines help.
Edit: Seems if i pull it out and insert it numerous time, theres about a 1 in 10 chance that i will get it to register in the menu, but selecting the Print from SD option shows nothing in the root. Tried FAT and FAT32. Not sure if this is just a hardware issue and i got a defect.

**Comment by martinbogo** [comment]
I'm having the same issue.  I can detect that the SD card is inserted, but cannot actually read a FAT, FAT16, or FAT32 formatted card.  It simply shows "No SD card"

**Comment by Blue-Marlin** [comment]
> I'm having the same issue.

So use the provided solution. Activate SD-support.
If even (low level) formatting the card does not help, open a new issue.

**Comment by martinbogo** [comment]
I was too terse in my reply -- I am having the same issue after:

= trying both version 1.0.2-1 and the current RC7
= defining SDSUPPORT 
= trying to reduce SPI speed ( half, quarter )
= checking the board to make sure both 3.3v and 5v are present
= defining SPI_SD_INIT_RATE 6, as well as SD_CHECK_AND_RETRY
= using a 1, 2, and 4GB SD card formatted FAT, FAT16, and FAT32

**Comment by thinkyhead** [comment]
See if low-level formatting the SD card helps. Be sure to back up your data first!

The cardreader library may be "too-quickly" rejecting fragmented SD cards when first inserted. A suggested solution is to try this change in `ultralcd.cpp` around line 2571 (`RCBugFix`):

``` diff
      if (sd_status) {
        card.initsd();
+       if (!card.cardOK) card.initsd();
        if (lcd_sd_status != 2) LCD_MESSAGEPGM(MSG_SD_INSERTED);
      }
```

The `M21` command will also try to re-init the sd card reader.

**Comment by Ilias123povetin** [comment]
Hello, I changed this line but nothing happend in marlin RC8( M21 works

**Comment by thinkyhead** [comment]
@Ilias123povetin

How's the `RCBugFix` branch performing at this time?

Have you tried doing a low-level format of your SD card?

**Comment by Ilias123povetin** [comment]
I will try rcbugfix now and try to formate now)) Sorry for my English I am Russian

**Comment by thinkyhead** [comment]
Your English is better than my Russian. If low-level format doesn't address it we can try some other stuff. Usually the problem is caused by an SD card that is too slow to respond on bootup.

**Comment by Ilias123povetin** [comment]
I have tried on another marlin version( i choosed some from internet not yours) and the card is working here) But it has a lot of lags and hasnt got  the functions what i need(

**Comment by Ilias123povetin** [comment]
And i changed 3 sd cards and all of them are not working(

**Comment by Ilias123povetin** [comment]
I think that the trouble is because the reader is learning it very fast and it isn,t in time because when i right m21 comand it see sd card...

**Comment by thinkyhead** [comment]
Try this:
``` diff
      if (sd_status) {
        card.initsd();
+       if (!card.cardOK) {
+         safe_delay(1000)
+         card.initsd();
+       }
        if (lcd_sd_status != 2) LCD_MESSAGEPGM(MSG_SD_INSERTED);
      }
```

**Comment by Ilias123povetin** [comment]
It didn't helped( Maybe it's because i have a DiscountSmartController not a Fullgrafic

**Comment by Ilias123povetin** [comment]
Mb i will send to you the files of the firmware where sd card works?

**Comment by Bob-the-Kuhn** [comment]
Did you try RCBugFix?  You can download it [here](https://github.com/MarlinFirmware/Marlin/tree/RCBugFix).

You'll need to manually move your machine specific items over to the new config files.

You might also look at issue #6249 .  They were having some strange SD card issues.

**Comment by Ilias123povetin** [comment]
Noting works(

**Comment by Ilias123povetin** [comment]
Nothing works on rc bug fix

**Comment by SilentZen** [comment]
I am using a Class 10 card which is detected as inserted but does not auto mount and says no sd detected.
Using M52 mounts it.
4GB card works fine without M52.
I am on recent bugfix version.
Thanks

**Comment by Siotma** [comment]
> I'm having the exact same problem and none of the SD related defines help.
Edit: Seems if i pull it out and insert it numerous time, theres about a 1 in 10 chance that i will get it to register in the menu, but selecting the Print from SD option shows nothing in the root. Tried FAT and FAT32. Not sure if this is just a hardware issue and i got a defect.

I had a very similar issue with a RepRapDiscount Full Graphic Smart Controller and I've just fixed it just adding one delay line as @thinkyhead suggested:

```diff
if (sd_status) {
+   safe_delay(1000); //FIX FOR MY FULL GRAPHIC SMART CONTROLLER
    card.initsd();
    if (lcd_sd_status != 2) LCD_MESSAGEPGM(MSG_SD_INSERTED);
}
```
To provide more information: I've been using a 4 line RepRapDiscount Smart Controller for 4 years without any problem with different cards, but today I have upgraded my printer with a Full Graphic one and found the problem: when I turn-on the printer, SD is recognized, but if I try to plug the SD while the printer is turned-on, it does show the "card inserted message" but still "No SD Card" is shown at the Menu.

As I say, adding that line of code at `line 4518` of `ultralcd.cpp` fixes the problem for me.
  
Edit: Just for information I'm using Marlin 1.1.6 and 2GB SD formatted in FAT

**Comment by Bob-the-Kuhn** [comment]
I've just added that line in bugfix-1.1.x

**Comment by madmax2** [comment]
I also have the same issue with my Reprap Discount Full Graphics Smart Controller .

I have tried the code - safe_delay(1000) but still not detecting any external SD card.

I am using marlin Marlin-bugfix-2.0.x version
Board = MKS Sbase 1.3

**Comment by thinkyhead** [comment]
@madmax2 — Please file a new issue. Closed old issues don't get the same attention as new open issues.

**Comment by giancarloandre** [comment]
My issue is the same and I think it might be a problem with the lcd  since it was printing properly the 2  first weeks then it started with the error “No sd car” even though it detects that the “ sd has been removed” when I remove it and “sd inserted” when I inserted. I tried with differents sd card but no answer seems to come. My next attemp will be to buy a new lcd

**Comment by gryzlov** [comment]
> My issue is the same and I think it might be a problem with the lcd since it was printing properly the 2 first weeks then it started with the error “No sd car” even though it detects that the “ sd has been removed” when I remove it and “sd inserted” when I inserted. I tried with differents sd card but no answer seems to come. My next attemp will be to buy a new lcd

Have same issue

**Comment by giancarloandre** [comment]
I did change the lcd and still the same problem no possible answer arised. I just kind of resigned to print with the lcd and instead I am printing from the serial port through the arduino and the repetier program

**Comment by adilrs** [comment]
Change SdFatConfig.h

 // Set USE_SOFTWARE_SPI nonzero to ALWAYS use Software SPI.
#define USE_SOFTWARE_SPI 1   // default 0

// Define software SPI pins so Mega can use unmodified 168/328 shields
#define SOFT_SPI_CS_PIN   53// default 10 // Software SPI chip select pin for the SD
#define SOFT_SPI_MOSI_PIN 51//default 11 // Software SPI Master Out Slave In pin
#define SOFT_SPI_MISO_PIN 50//default 12 // Software SPI Master In Slave Out pin
#define SOFT_SPI_SCK_PIN  52//default 13 // Software SPI Clock pin
