### ISSUE TITLE
[2.0.x] How to fix pin interrupt tests?

### ISSUE THREAD

**Issue by thinkyhead** [MarlinFirmware/Marlin#9632]
As seen in #9243, some platforms can only test pin interrupts at runtime. This breaks `static_assert`.

```
non-constant condition for static assertion

on this define:

#define digitalPinToPCICR(p) ( (((p) >= 0) && ((p) <= 31)) ? (&PCICR) : ((uint8_t *)0) )

invoked by:

static_assert(digitalPinToPCICR(X_MIN_PIN) != NULL, "X_MIN_PIN is not interrupt-capable");
static_assert(digitalPinToPCICR(Y_MIN_PIN) != NULL, "Y_MIN_PIN is not interrupt-capable");
static_assert(digitalPinToPCICR(Z_MIN_PIN) != NULL, "Z_MIN_PIN is not interrupt-capable");

in file endstop_interrupts.h.
```
Since pins for each platform are well-defined, is there a way to do this statically? If needed, we can add a new macro so `digitalPinToPCICR` is still usable at runtime. For example, can we have a companion to `digitalPinToPCICR` for the above example like this?
```cpp
#define digitalPinHasPCICR(p) WITHIN(p, 0, 31)
#define digitalPinToPCICR(p) (digitalPinHasPCICR(p) ? &PCICR : (uint8_t *)0)

```

**Comment by thinkyhead** [comment]
@Bob-the-Kuhn — Did this get fixed with our last scrub of the pins and pinsDebug code?

**Comment by Bob-the-Kuhn** [comment]
I didn't do anything on this.

**Comment by boelle** [comment]
@thinkyhead Another one that needs to be closed. Sorry, I got bored.

**Comment by rewolff** [comment]
I'm currently running into this issue. I'd say it's not fixed. arduino 1.9.0-beta and marlin-from-git IIRC....

**Comment by CKCMorgoth** [comment]
Same as rewolff, I am running in this error and have no idea what to do

**Comment by thinkyhead** [comment]
Unable to reproduce. Please supply your configurations for testing.

**Comment by ThomasTL** [comment]
I am also currently running into the same issue. I tried to compile Marlin 1.1.x, bugfix Marlin 1.1.x and bugfix Marlin 2.0.x ... Same issue for all. So i also believe this is not yet fixed.
I am using:
* MacBook Pro (config as shown on the screenshot).
* Arduino IDE 1.8.10
* Anet A8 board definition from Skynet3D (attached in hardware.zip file)
* Marlin Configuration.h and Configuration_adv.h for Anet A8 unmodified beside the define for the printer name (attached in Marlin_config_h.zip).
If you need more information or anything else for testing, please do let me know @thinkyhead.
Thanks for the help.

[Marlin_config_h.zip](https://github.com/MarlinFirmware/Marlin/files/3692985/Marlin_config_h.zip)
[hardware.zip](https://github.com/MarlinFirmware/Marlin/files/3692983/hardware.zip)
[compile_errors.txt](https://github.com/MarlinFirmware/Marlin/files/3692979/compile_errors.txt)
<img width="577" alt="Screenshot 2019-10-05 at 3 02 32 PM" src="https://user-images.githubusercontent.com/8722814/66252107-8f26e880-e781-11e9-928a-ba8c208988c3.png">

**Comment by krizz696** [comment]
same issue after flashing Marlin 2.0.x 

Arduino: 1.8.10 (Windows 10), Board:"Anet V1.0 (Optiboot)"

In file included from sketch\src\module\endstops.cpp:36:0:

c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\hal_avr\endstop_interrupts.h: In function 'void setup_endstop_interrupts()':

c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\hal_avr\endstop_interrupts.h:119:7: error: non-constant condition for static assertion

       static_assert(digitalPinToPCICR(X_MIN_PIN), "X_MIN_PIN is not interrupt-capable");

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:257:0,

                 from c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\shared\marduino.h:36,

                 from c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\hal_avr\hal.h:21,

                 from c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\hal.h:26,

                 from c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\inc\marlinconfig.h:30,

                 from sketch\src\module\endstops.h:28,

                 from sketch\src\module\endstops.cpp:27:

C:\Users\matun\AppData\Local\Arduino15\packages\anet\hardware\avr\1.0.2\variants\sanguino/pins_arduino.h:92:66: error: reinterpret_cast from integer to pointer

 #define digitalPinToPCICR(p)    ( (((p) >= 0) && ((p) <= 31)) ? (&PCICR) : ((uint8_t *)0) )

                                                                 ~^~~~~~~

c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\hal_avr\endstop_interrupts.h:119:21: note: in expansion of macro 'digitalPinToPCICR'

       static_assert(digitalPinToPCICR(X_MIN_PIN), "X_MIN_PIN is not interrupt-capable");

                     ^~~~~~~~~~~~~~~~~

In file included from sketch\src\module\endstops.cpp:36:0:

c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\hal_avr\endstop_interrupts.h:135:7: error: non-constant condition for static assertion

       static_assert(digitalPinToPCICR(Y_MIN_PIN), "Y_MIN_PIN is not interrupt-capable");

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:257:0,

                 from c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\shared\marduino.h:36,

                 from c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\hal_avr\hal.h:21,

                 from c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\hal.h:26,

                 from c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\inc\marlinconfig.h:30,

                 from sketch\src\module\endstops.h:28,

                 from sketch\src\module\endstops.cpp:27:

C:\Users\matun\AppData\Local\Arduino15\packages\anet\hardware\avr\1.0.2\variants\sanguino/pins_arduino.h:92:66: error: reinterpret_cast from integer to pointer

 #define digitalPinToPCICR(p)    ( (((p) >= 0) && ((p) <= 31)) ? (&PCICR) : ((uint8_t *)0) )

                                                                 ~^~~~~~~

c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\hal_avr\endstop_interrupts.h:135:21: note: in expansion of macro 'digitalPinToPCICR'

       static_assert(digitalPinToPCICR(Y_MIN_PIN), "Y_MIN_PIN is not interrupt-capable");

                     ^~~~~~~~~~~~~~~~~

In file included from sketch\src\module\endstops.cpp:36:0:

c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\hal_avr\endstop_interrupts.h:151:7: error: non-constant condition for static assertion

       static_assert(digitalPinToPCICR(Z_MIN_PIN), "Z_MIN_PIN is not interrupt-capable");

       ^~~~~~~~~~~~~

In file included from C:\Program Files (x86)\Arduino\hardware\arduino\avr\cores\arduino/Arduino.h:257:0,

                 from c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\shared\marduino.h:36,

                 from c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\hal_avr\hal.h:21,

                 from c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\hal.h:26,

                 from c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\inc\marlinconfig.h:30,

                 from sketch\src\module\endstops.h:28,

                 from sketch\src\module\endstops.cpp:27:

C:\Users\matun\AppData\Local\Arduino15\packages\anet\hardware\avr\1.0.2\variants\sanguino/pins_arduino.h:92:66: error: reinterpret_cast from integer to pointer

 #define digitalPinToPCICR(p)    ( (((p) >= 0) && ((p) <= 31)) ? (&PCICR) : ((uint8_t *)0) )

                                                                 ~^~~~~~~

c:\users\matun\appdata\local\temp\arduino_build_203301\sketch\src\hal\hal_avr\endstop_interrupts.h:151:21: note: in expansion of macro 'digitalPinToPCICR'

       static_assert(digitalPinToPCICR(Z_MIN_PIN), "Z_MIN_PIN is not interrupt-capable");

                     ^~~~~~~~~~~~~~~~~

Meerdere bibliotheken gevonden voor "U8glib.h"
Gebruikt: C:\Users\matun\Documents\Arduino\libraries\U8glib
exit status 1
Fout bij het compileren voor board Anet V1.0 (Optiboot)

**Comment by krizz696** [comment]
Tools > Boards > Board Manager. On the Arduino AVR Boards, select and install the previous version.

**Comment by thinkyhead** [comment]
> select and install the previous version.

Select and install the previous Anet A8 board definition? That might work!

**Comment by krizz696** [comment]
previous version of the arduino avr boards . not anet boards .

**Comment by ThomasTL** [comment]
Ok, I did what was suggested by @krizz696, I installed version 1.6.23 of Arduino AVR boards.
And: `Done compiling`, that did the trick! 
Thanks very much, @krizz696 & @thinkyhead!

**Comment by abhijit-kamble** [comment]
I tried to compile Marlin 1.1.x ran into the same issue then I installed version 1.6.23 of arduino then  I got the following compilation error: 
```
**sketch\endstops.cpp.o (symbol from plugin): In function `Endstops::live_state':

(.text+0x0): multiple definition of `handleEncoder_Intr_01()'

sketch\Marlin_main.cpp.o (symbol from plugin):(.text+0x0): first defined here

c:/users/abhijit/appdata/local/arduino15/packages/arduino/tools/avr-gcc/4.9.2-atmel3.5.4-arduino2/bin/../lib/gcc/avr/4.9.2/../../../../avr/bin/ld.exe: Disabling relaxation: it will not work with multiple definitions

sketch\endstops.cpp.o (symbol from plugin): In function `Endstops::live_state':

(.text+0x0): multiple definition of `handleEncoder_Intr_02()'

sketch\Marlin_main.cpp.o (symbol from plugin):(.text+0x0): first defined here

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Mega or Mega 2560.**
```
Please check out this issue.

**Comment by thinkyhead** [comment]
If you can find `handleEncoder_Intr_02` in Marlin, then we'll be happy to fix its issue!

**Comment by rewolff** [comment]
@abhi667 This issue is about a static interrupt line check, your issue has something to do with an interrupt routine. That's a different issue. 
What Thinkyhead is trying to say is that your issue might not even be a Marlin issue but one in your arduino IDE. i.e. not something the guys here can fix. With the arduino IDE it is recommended to use the latest version, or the one just before that. Note that arduino has a weird version numbering, so that the highest number you can find is NOT the latest.

**Comment by ThomasTL** [comment]
@abhi667 I had some weird issues with Arduino IDE before I managed to successfully compile Marlin for my 3D printer. I have been battling for a while on issues that were not related to Marlin but to the IDE.
One thing that worked for me is to rename the `Arduino15` folder in `/Users/username/Library` and relaunch the app to force the creation of a new `Arduino15` directory in the same path (on Mac OS).
On Windows, you need to uninstall Arduino IDE, rename the `Arduino15` folder from your install path (most likely `c:/users/abhijit/appdata/local/arduino15`, as I can read from the traces in your message), and reinstall Arduino IDE (check also that it this folder is not been installed in a different location as well).
This could fix your issue as well.
Cheers.

**Comment by jaknowwho** [comment]
So I'm not particularly wise in the details of this coding, but I'm having the same issue @ThomasTL  had with the non-constant condition for static assertion. Which program/file did you role back to the previous version? (I know website coding a little, that's about it. If you could help me understand what it was you changed that would be awesome!)

**Comment by tophat17** [comment]
> Ok, I did what was suggested by @krizz696, I installed version 1.6.23 of Arduino AVR boards.
> And: `Done compiling`, that did the trick!
> Thanks very much, @krizz696 & @thinkyhead!

Worked for me!
